'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class es
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("appMedico.es", GetType(es).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Alerta de Cierre.
        '''</summary>
        Friend Shared ReadOnly Property alertadecierre() As String
            Get
                Return ResourceManager.GetString("alertadecierre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apellidos.
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apto.
        '''</summary>
        Friend Shared ReadOnly Property apto() As String
            Get
                Return ResourceManager.GetString("apto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aviso.
        '''</summary>
        Friend Shared ReadOnly Property aviso() As String
            Get
                Return ResourceManager.GetString("aviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aviso antes de Cierre.
        '''</summary>
        Friend Shared ReadOnly Property avisoantesdecierre() As String
            Get
                Return ResourceManager.GetString("avisoantesdecierre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Barrio.
        '''</summary>
        Friend Shared ReadOnly Property barrio() As String
            Get
                Return ResourceManager.GetString("barrio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Bienvenido.
        '''</summary>
        Friend Shared ReadOnly Property bienvenido() As String
            Get
                Return ResourceManager.GetString("bienvenido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Calle.
        '''</summary>
        Friend Shared ReadOnly Property calle() As String
            Get
                Return ResourceManager.GetString("calle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat Activo.
        '''</summary>
        Friend Shared ReadOnly Property chatactivo() As String
            Get
                Return ResourceManager.GetString("chatactivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No hay solicitudes de chat.
        '''</summary>
        Friend Shared ReadOnly Property chatvacio() As String
            Get
                Return ResourceManager.GetString("chatvacio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Desea enviar ua copia del chat al email del paciente?.
        '''</summary>
        Friend Shared ReadOnly Property copiaemailapaciente() As String
            Get
                Return ResourceManager.GetString("copiaemailapaciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doc. Identidad.
        '''</summary>
        Friend Shared ReadOnly Property docidentidad() As String
            Get
                Return ResourceManager.GetString("docidentidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento identidad.
        '''</summary>
        Friend Shared ReadOnly Property documento() As String
            Get
                Return ResourceManager.GetString("documento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedades Pre Existentes.
        '''</summary>
        Friend Shared ReadOnly Property enfermedadespreexistentes() As String
            Get
                Return ResourceManager.GetString("enfermedadespreexistentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property err() As String
            Get
                Return ResourceManager.GetString("err", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al cargar enfermedades pre Existentes !.
        '''</summary>
        Friend Shared ReadOnly Property errorcargarenfermedadespreexistentes() As String
            Get
                Return ResourceManager.GetString("errorcargarenfermedadespreexistentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al cargar los mensajes recibidos !.
        '''</summary>
        Friend Shared ReadOnly Property errorcargarmensajesrecibidos() As String
            Get
                Return ResourceManager.GetString("errorcargarmensajesrecibidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al chequear mensajes.
        '''</summary>
        Friend Shared ReadOnly Property errorchequearmensaje() As String
            Get
                Return ResourceManager.GetString("errorchequearmensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al traer los datos del paciente.
        '''</summary>
        Friend Shared ReadOnly Property errordatospaciente() As String
            Get
                Return ResourceManager.GetString("errordatospaciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de Acceso.
        '''</summary>
        Friend Shared ReadOnly Property errordeacceso() As String
            Get
                Return ResourceManager.GetString("errordeacceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de usuario o contraseña, verifica.
        '''</summary>
        Friend Shared ReadOnly Property errordelogin() As String
            Get
                Return ResourceManager.GetString("errordelogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al enviar el chat a espera.
        '''</summary>
        Friend Shared ReadOnly Property errorenviarchatespera() As String
            Get
                Return ResourceManager.GetString("errorenviarchatespera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al enviar el mensaje.
        '''</summary>
        Friend Shared ReadOnly Property errorenviarmensaje() As String
            Get
                Return ResourceManager.GetString("errorenviarmensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al intentar marcar mensaje !.
        '''</summary>
        Friend Shared ReadOnly Property errorintentarmarcarmensaje() As String
            Get
                Return ResourceManager.GetString("errorintentarmarcarmensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al registrar el cierre del chat.
        '''</summary>
        Friend Shared ReadOnly Property errorregistrarcierrechat() As String
            Get
                Return ResourceManager.GetString("errorregistrarcierrechat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al verificar el estado de la sesion.
        '''</summary>
        Friend Shared ReadOnly Property errorverificarestadosesion() As String
            Get
                Return ResourceManager.GetString("errorverificarestadosesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al verificar sesiones en espera.
        '''</summary>
        Friend Shared ReadOnly Property errorverificarsesionesespera() As String
            Get
                Return ResourceManager.GetString("errorverificarsesionesespera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esquina.
        '''</summary>
        Friend Shared ReadOnly Property esquina() As String
            Get
                Return ResourceManager.GetString("esquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de Nacimiento.
        '''</summary>
        Friend Shared ReadOnly Property fechanacimiento() As String
            Get
                Return ResourceManager.GetString("fechanacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha Registro.
        '''</summary>
        Friend Shared ReadOnly Property fecharegistro() As String
            Get
                Return ResourceManager.GetString("fecharegistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Finalizar Chat.
        '''</summary>
        Friend Shared ReadOnly Property finalizarchat() As String
            Get
                Return ResourceManager.GetString("finalizarchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingresar.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingreso al Sistema.
        '''</summary>
        Friend Shared ReadOnly Property ingresoalsistema() As String
            Get
                Return ResourceManager.GetString("ingresoalsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingresa tus credenciales para acceder al sistema.
        '''</summary>
        Friend Shared ReadOnly Property leyendalogin() As String
            Get
                Return ResourceManager.GetString("leyendalogin", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se pudieron cargar los sintomas del paciente !.
        '''</summary>
        Friend Shared ReadOnly Property nocargaronsintomaspaciente() As String
            Get
                Return ResourceManager.GetString("nocargaronsintomaspaciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No puede cerrar la aplicacion si existe un chat en proceso !.
        '''</summary>
        Friend Shared ReadOnly Property nocerrarchatenproceso() As String
            Get
                Return ResourceManager.GetString("nocerrarchatenproceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre del Medico.
        '''</summary>
        Friend Shared ReadOnly Property nombremedico() As String
            Get
                Return ResourceManager.GetString("nombremedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombres.
        '''</summary>
        Friend Shared ReadOnly Property nombres() As String
            Get
                Return ResourceManager.GetString("nombres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Numero.
        '''</summary>
        Friend Shared ReadOnly Property numero() As String
            Get
                Return ResourceManager.GetString("numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En Linea.
        '''</summary>
        Friend Shared ReadOnly Property online() As String
            Get
                Return ResourceManager.GetString("online", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El paciente ha cerrado la sesion de chat.
        '''</summary>
        Friend Shared ReadOnly Property pacientecerrosesion() As String
            Get
                Return ResourceManager.GetString("pacientecerrosesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Poner en espera.
        '''</summary>
        Friend Shared ReadOnly Property ponerespera() As String
            Get
                Return ResourceManager.GetString("ponerespera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estas seguro de finalizar el chat ?.
        '''</summary>
        Friend Shared ReadOnly Property segurofinalizarchat() As String
            Get
                Return ResourceManager.GetString("segurofinalizarchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintomas Ingresados en la consulta.
        '''</summary>
        Friend Shared ReadOnly Property sintomasingresados() As String
            Get
                Return ResourceManager.GetString("sintomasingresados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver Chat.
        '''</summary>
        Friend Shared ReadOnly Property verchat() As String
            Get
                Return ResourceManager.GetString("verchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver datos paciente.
        '''</summary>
        Friend Shared ReadOnly Property verdatospaciente() As String
            Get
                Return ResourceManager.GetString("verdatospaciente", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
