'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("appUsuario.en", GetType(en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please wait while we prepare your report ....
        '''</summary>
        Friend Shared ReadOnly Property aguardapreparamosinforme() As String
            Get
                Return ResourceManager.GetString("aguardapreparamosinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Last Name.
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Suit.
        '''</summary>
        Friend Shared ReadOnly Property apto() As String
            Get
                Return ResourceManager.GetString("apto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirm action.
        '''</summary>
        Friend Shared ReadOnly Property avisoconfirmacion() As String
            Get
                Return ResourceManager.GetString("avisoconfirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Locate.
        '''</summary>
        Friend Shared ReadOnly Property barrio() As String
            Get
                Return ResourceManager.GetString("barrio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change of language.
        '''</summary>
        Friend Shared ReadOnly Property cambioidoma() As String
            Get
                Return ResourceManager.GetString("cambioidoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This change requires that you have to close and open the application, are you sure?.
        '''</summary>
        Friend Shared ReadOnly Property cambiorequierereiniciar() As String
            Get
                Return ResourceManager.GetString("cambiorequierereiniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat.
        '''</summary>
        Friend Shared ReadOnly Property chat() As String
            Get
                Return ResourceManager.GetString("chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log out.
        '''</summary>
        Friend Shared ReadOnly Property cierredesesion() As String
            Get
                Return ResourceManager.GetString("cierredesesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contact us if there are differences with your personal data..
        '''</summary>
        Friend Shared ReadOnly Property comunicateconnosotros() As String
            Get
                Return ResourceManager.GetString("comunicateconnosotros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Consultation.
        '''</summary>
        Friend Shared ReadOnly Property consulta() As String
            Get
                Return ResourceManager.GetString("consulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tell us what is your main symptom ...?.
        '''</summary>
        Friend Shared ReadOnly Property cualestuprincipalsintoma() As String
            Get
                Return ResourceManager.GetString("cualestuprincipalsintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Data.
        '''</summary>
        Friend Shared ReadOnly Property datos() As String
            Get
                Return ResourceManager.GetString("datos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a do you want to enter a new symptom?.
        '''</summary>
        Friend Shared ReadOnly Property deseaingresarnuevosintoma() As String
            Get
                Return ResourceManager.GetString("deseaingresarnuevosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnostics received.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticosrecibidos() As String
            Get
                Return ResourceManager.GetString("diagnosticosrecibidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Address.
        '''</summary>
        Friend Shared ReadOnly Property direccion() As String
            Get
                Return ResourceManager.GetString("direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Identification Id.
        '''</summary>
        Friend Shared ReadOnly Property docidentidad() As String
            Get
                Return ResourceManager.GetString("docidentidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctor.
        '''</summary>
        Friend Shared ReadOnly Property doctor() As String
            Get
                Return ResourceManager.GetString("doctor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Document.
        '''</summary>
        Friend Shared ReadOnly Property Documento() As String
            Get
                Return ResourceManager.GetString("Documento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The doctor ended the chat session.
        '''</summary>
        Friend Shared ReadOnly Property elmedicocerrosesion() As String
            Get
                Return ResourceManager.GetString("elmedicocerrosesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The patient has left the chat.
        '''</summary>
        Friend Shared ReadOnly Property elpacientehasalidodelchat() As String
            Get
                Return ResourceManager.GetString("elpacientehasalidodelchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The symptom is already entered.
        '''</summary>
        Friend Shared ReadOnly Property elsistomayaestaingresado() As String
            Get
                Return ResourceManager.GetString("elsistomayaestaingresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wait.
        '''</summary>
        Friend Shared ReadOnly Property enespera() As String
            Get
                Return ResourceManager.GetString("enespera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fail.
        '''</summary>
        Friend Shared ReadOnly Property err() As String
            Get
                Return ResourceManager.GetString("err", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Access Denegate.
        '''</summary>
        Friend Shared ReadOnly Property erroracceso() As String
            Get
                Return ResourceManager.GetString("erroracceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Data access error.
        '''</summary>
        Friend Shared ReadOnly Property erroraccesodatos() As String
            Get
                Return ResourceManager.GetString("erroraccesodatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The configuration file cannot be found. Can&apos;t continue.
        '''</summary>
        Friend Shared ReadOnly Property errorarchivo() As String
            Get
                Return ResourceManager.GetString("errorarchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error trying to register chat cancellation..
        '''</summary>
        Friend Shared ReadOnly Property errorcancelarsesionchat() As String
            Get
                Return ResourceManager.GetString("errorcancelarsesionchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wrong document document or password.
        '''</summary>
        Friend Shared ReadOnly Property errordatosacceso() As String
            Get
                Return ResourceManager.GetString("errordatosacceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error sending message, try again ....
        '''</summary>
        Friend Shared ReadOnly Property errorenviarmensaje() As String
            Get
                Return ResourceManager.GetString("errorenviarmensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to save chat session.
        '''</summary>
        Friend Shared ReadOnly Property errorguardarsesionchat() As String
            Get
                Return ResourceManager.GetString("errorguardarsesionchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to retrieve data.
        '''</summary>
        Friend Shared ReadOnly Property errorrecuperardatos() As String
            Get
                Return ResourceManager.GetString("errorrecuperardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spanish.
        '''</summary>
        Friend Shared ReadOnly Property espanol() As String
            Get
                Return ResourceManager.GetString("espanol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Waiting Doctor ....
        '''</summary>
        Friend Shared ReadOnly Property esperandomedico() As String
            Get
                Return ResourceManager.GetString("esperandomedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Stree corner.
        '''</summary>
        Friend Shared ReadOnly Property esquina() As String
            Get
                Return ResourceManager.GetString("esquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a State.
        '''</summary>
        Friend Shared ReadOnly Property estado() As String
            Get
                Return ResourceManager.GetString("estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registration date.
        '''</summary>
        Friend Shared ReadOnly Property fecharegistro() As String
            Get
                Return ResourceManager.GetString("fecharegistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a We have prepared the following report for you according to the symptoms you have entered. Please start a chat conversation with the doctor..
        '''</summary>
        Friend Shared ReadOnly Property hemospreparadoinforme() As String
            Get
                Return ResourceManager.GetString("hemospreparadoinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a History.
        '''</summary>
        Friend Shared ReadOnly Property historia() As String
            Get
                Return ResourceManager.GetString("historia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat history.
        '''</summary>
        Friend Shared ReadOnly Property historicochat() As String
            Get
                Return ResourceManager.GetString("historicochat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a English.
        '''</summary>
        Friend Shared ReadOnly Property ingles() As String
            Get
                Return ResourceManager.GetString("ingles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login.
        '''</summary>
        Friend Shared ReadOnly Property ingresoalsistema() As String
            Get
                Return ResourceManager.GetString("ingresoalsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start Chat.
        '''</summary>
        Friend Shared ReadOnly Property iniciarchat() As String
            Get
                Return ResourceManager.GetString("iniciarchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start consultation.
        '''</summary>
        Friend Shared ReadOnly Property iniciarconsulta() As String
            Get
                Return ResourceManager.GetString("iniciarconsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Language.
        '''</summary>
        Friend Shared ReadOnly Property lenguaje() As String
            Get
                Return ResourceManager.GetString("lenguaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a More than 80 years betting on the health of our members. A big family protects you..
        '''</summary>
        Friend Shared ReadOnly Property leyendainicial() As String
            Get
                Return ResourceManager.GetString("leyendainicial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a list of symptoms.
        '''</summary>
        Friend Shared ReadOnly Property listadesintomas() As String
            Get
                Return ResourceManager.GetString("listadesintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hi, thanks for using Triage. We will try to guide you so that you can later consult your doctor. Let&apos;s start doing an evaluation.
        '''</summary>
        Friend Shared ReadOnly Property mensajeinicial() As String
            Get
                Return ResourceManager.GetString("mensajeinicial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No.
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There are no pathologies with the symptoms that you have entered! You can start a session with a doctor to consult.
        '''</summary>
        Friend Shared ReadOnly Property noexistenpatologias() As String
            Get
                Return ResourceManager.GetString("noexistenpatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New consultation.
        '''</summary>
        Friend Shared ReadOnly Property nuevaconsulta() As String
            Get
                Return ResourceManager.GetString("nuevaconsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a N`.
        '''</summary>
        Friend Shared ReadOnly Property numero() As String
            Get
                Return ResourceManager.GetString("numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Online.
        '''</summary>
        Friend Shared ReadOnly Property online() As String
            Get
                Return ResourceManager.GetString("online", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnosed pathologies.
        '''</summary>
        Friend Shared ReadOnly Property patologiasdiagnosticadas() As String
            Get
                Return ResourceManager.GetString("patologiasdiagnosticadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pre-existing pathologies.
        '''</summary>
        Friend Shared ReadOnly Property patologiaspreexistentes() As String
            Get
                Return ResourceManager.GetString("patologiaspreexistentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Press View Report so that we can generate a diagnosis according to the symptoms you have entered. Do not stop consulting your doctor via chat, remember that this diagnosis does not replace the consultation of a professional..
        '''</summary>
        Friend Shared ReadOnly Property presionaparaverinforme() As String
            Get
                Return ResourceManager.GetString("presionaparaverinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a What other symptom do you have, enter it ....
        '''</summary>
        Friend Shared ReadOnly Property queotrosintomatienes() As String
            Get
                Return ResourceManager.GetString("queotrosintomatienes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remeber my data.
        '''</summary>
        Friend Shared ReadOnly Property recordarmisdatos() As String
            Get
                Return ResourceManager.GetString("recordarmisdatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a About.
        '''</summary>
        Friend Shared ReadOnly Property sabermas() As String
            Get
                Return ResourceManager.GetString("sabermas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure to close the application?.
        '''</summary>
        Friend Shared ReadOnly Property segurocerraraplicacion() As String
            Get
                Return ResourceManager.GetString("segurocerraraplicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure to close the chat session?.
        '''</summary>
        Friend Shared ReadOnly Property segurocerrarsesion() As String
            Get
                Return ResourceManager.GetString("segurocerrarsesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Yes.
        '''</summary>
        Friend Shared ReadOnly Property si() As String
            Get
                Return ResourceManager.GetString("si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Do you feel another symptom? Enter it ....
        '''</summary>
        Friend Shared ReadOnly Property sientesotrosintoma() As String
            Get
                Return ResourceManager.GetString("sientesotrosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Next.
        '''</summary>
        Friend Shared ReadOnly Property siguiente() As String
            Get
                Return ResourceManager.GetString("siguiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a If you have another symptom, enter it ....
        '''</summary>
        Friend Shared ReadOnly Property sitienesotrosintoma() As String
            Get
                Return ResourceManager.GetString("sitienesotrosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phones.
        '''</summary>
        Friend Shared ReadOnly Property telefonos() As String
            Get
                Return ResourceManager.GetString("telefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You have another symptom, enter it ....
        '''</summary>
        Friend Shared ReadOnly Property tienesotrosintoma() As String
            Get
                Return ResourceManager.GetString("tienesotrosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a You.
        '''</summary>
        Friend Shared ReadOnly Property tu() As String
            Get
                Return ResourceManager.GetString("tu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registered user.
        '''</summary>
        Friend Shared ReadOnly Property usuarioregistrado() As String
            Get
                Return ResourceManager.GetString("usuarioregistrado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Personal data.
        '''</summary>
        Friend Shared ReadOnly Property verificarinformacionpersonal() As String
            Get
                Return ResourceManager.GetString("verificarinformacionpersonal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a View Report.
        '''</summary>
        Friend Shared ReadOnly Property verinforme() As String
            Get
                Return ResourceManager.GetString("verinforme", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
