'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class es
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("appUsuario.es", GetType(es).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aguarda mientras preparamos tu informe....
        '''</summary>
        Friend Shared ReadOnly Property aguardapreparamosinforme() As String
            Get
                Return ResourceManager.GetString("aguardapreparamosinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apellidos.
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apto.
        '''</summary>
        Friend Shared ReadOnly Property apto() As String
            Get
                Return ResourceManager.GetString("apto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmar Accion.
        '''</summary>
        Friend Shared ReadOnly Property avisoconfirmacion() As String
            Get
                Return ResourceManager.GetString("avisoconfirmacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ayuda.
        '''</summary>
        Friend Shared ReadOnly Property ayuda() As String
            Get
                Return ResourceManager.GetString("ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Barrio.
        '''</summary>
        Friend Shared ReadOnly Property barrio() As String
            Get
                Return ResourceManager.GetString("barrio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cambio de Idioma.
        '''</summary>
        Friend Shared ReadOnly Property cambioidoma() As String
            Get
                Return ResourceManager.GetString("cambioidoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Este cambio requiere que tengas que cerrar y abrir la aplicacion, estas seguro?.
        '''</summary>
        Friend Shared ReadOnly Property cambiorequierereiniciar() As String
            Get
                Return ResourceManager.GetString("cambiorequierereiniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat.
        '''</summary>
        Friend Shared ReadOnly Property chat() As String
            Get
                Return ResourceManager.GetString("chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cierre de Sesion.
        '''</summary>
        Friend Shared ReadOnly Property cierredesesion() As String
            Get
                Return ResourceManager.GetString("cierredesesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Comunicate con nosotros si existen diferencias con tus datos personales..
        '''</summary>
        Friend Shared ReadOnly Property comunicateconnosotros() As String
            Get
                Return ResourceManager.GetString("comunicateconnosotros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Consulta.
        '''</summary>
        Friend Shared ReadOnly Property consulta() As String
            Get
                Return ResourceManager.GetString("consulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cuentanos cual es tu princial sintoma...?.
        '''</summary>
        Friend Shared ReadOnly Property cualestuprincipalsintoma() As String
            Get
                Return ResourceManager.GetString("cualestuprincipalsintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Datos.
        '''</summary>
        Friend Shared ReadOnly Property datos() As String
            Get
                Return ResourceManager.GetString("datos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Deseas ingresar un nuevo sintoma?.
        '''</summary>
        Friend Shared ReadOnly Property deseaingresarnuevosintoma() As String
            Get
                Return ResourceManager.GetString("deseaingresarnuevosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnosticos recibidos.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticosrecibidos() As String
            Get
                Return ResourceManager.GetString("diagnosticosrecibidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Direccion.
        '''</summary>
        Friend Shared ReadOnly Property direccion() As String
            Get
                Return ResourceManager.GetString("direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento de identidad.
        '''</summary>
        Friend Shared ReadOnly Property docidentidad() As String
            Get
                Return ResourceManager.GetString("docidentidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctor.
        '''</summary>
        Friend Shared ReadOnly Property doctor() As String
            Get
                Return ResourceManager.GetString("doctor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento.
        '''</summary>
        Friend Shared ReadOnly Property documento() As String
            Get
                Return ResourceManager.GetString("documento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El Medico finalizo la sesion de chat.
        '''</summary>
        Friend Shared ReadOnly Property elmedicocerrosesion() As String
            Get
                Return ResourceManager.GetString("elmedicocerrosesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El paciente ha salido del chat.
        '''</summary>
        Friend Shared ReadOnly Property elpacientehasalidodelchat() As String
            Get
                Return ResourceManager.GetString("elpacientehasalidodelchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El sintoma ya esta ingresado.
        '''</summary>
        Friend Shared ReadOnly Property elsistomayaestaingresado() As String
            Get
                Return ResourceManager.GetString("elsistomayaestaingresado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En espera.
        '''</summary>
        Friend Shared ReadOnly Property enespera() As String
            Get
                Return ResourceManager.GetString("enespera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property err() As String
            Get
                Return ResourceManager.GetString("err", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de acceso.
        '''</summary>
        Friend Shared ReadOnly Property erroracceso() As String
            Get
                Return ResourceManager.GetString("erroracceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de acceso a datos.
        '''</summary>
        Friend Shared ReadOnly Property erroraccesodatos() As String
            Get
                Return ResourceManager.GetString("erroraccesodatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se encuentra el archivo de configuracion. No puede continuar.
        '''</summary>
        Friend Shared ReadOnly Property errorarchivo() As String
            Get
                Return ResourceManager.GetString("errorarchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al intentar registrar la cancelacion del chat..
        '''</summary>
        Friend Shared ReadOnly Property errorcancelarsesionchat() As String
            Get
                Return ResourceManager.GetString("errorcancelarsesionchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Numero de documento o contraseña incorrecta.
        '''</summary>
        Friend Shared ReadOnly Property errordatosacceso() As String
            Get
                Return ResourceManager.GetString("errordatosacceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al enviar el mensaje, intente nuevamente....
        '''</summary>
        Friend Shared ReadOnly Property errorenviarmensaje() As String
            Get
                Return ResourceManager.GetString("errorenviarmensaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al guardar la sesion de chat.
        '''</summary>
        Friend Shared ReadOnly Property errorguardarsesionchat() As String
            Get
                Return ResourceManager.GetString("errorguardarsesionchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al recuperar los datos.
        '''</summary>
        Friend Shared ReadOnly Property errorrecuperardatos() As String
            Get
                Return ResourceManager.GetString("errorrecuperardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Español.
        '''</summary>
        Friend Shared ReadOnly Property espanol() As String
            Get
                Return ResourceManager.GetString("espanol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esperando Medico....
        '''</summary>
        Friend Shared ReadOnly Property esperandomedico() As String
            Get
                Return ResourceManager.GetString("esperandomedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esquina.
        '''</summary>
        Friend Shared ReadOnly Property esquina() As String
            Get
                Return ResourceManager.GetString("esquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estado.
        '''</summary>
        Friend Shared ReadOnly Property estado() As String
            Get
                Return ResourceManager.GetString("estado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Fecha de registro.
        '''</summary>
        Friend Shared ReadOnly Property fecharegistro() As String
            Get
                Return ResourceManager.GetString("fecharegistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hemos preparado el siguiente informe para ti de acuerdo a los sintomas que has ingresado. Por favor inicia una conversacion por chat con el medico..
        '''</summary>
        Friend Shared ReadOnly Property hemospreparadoinforme() As String
            Get
                Return ResourceManager.GetString("hemospreparadoinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Historia.
        '''</summary>
        Friend Shared ReadOnly Property historia() As String
            Get
                Return ResourceManager.GetString("historia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Historico de chat.
        '''</summary>
        Friend Shared ReadOnly Property historicochat() As String
            Get
                Return ResourceManager.GetString("historicochat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingles.
        '''</summary>
        Friend Shared ReadOnly Property ingles() As String
            Get
                Return ResourceManager.GetString("ingles", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingresar.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingreso al Sistema.
        '''</summary>
        Friend Shared ReadOnly Property ingresoalsistema() As String
            Get
                Return ResourceManager.GetString("ingresoalsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Iniciar Chat.
        '''</summary>
        Friend Shared ReadOnly Property iniciarchat() As String
            Get
                Return ResourceManager.GetString("iniciarchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Iniciar consulta.
        '''</summary>
        Friend Shared ReadOnly Property iniciarconsulta() As String
            Get
                Return ResourceManager.GetString("iniciarconsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lenguaje.
        '''</summary>
        Friend Shared ReadOnly Property lenguaje() As String
            Get
                Return ResourceManager.GetString("lenguaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mas de 80 años apostando a la saludar de nuestros afiliados. Una gran familia te protege..
        '''</summary>
        Friend Shared ReadOnly Property leyendainicial() As String
            Get
                Return ResourceManager.GetString("leyendainicial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lista de Sintomas.
        '''</summary>
        Friend Shared ReadOnly Property listadesintomas() As String
            Get
                Return ResourceManager.GetString("listadesintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hola, gracias por utilizar Triage. Trataremos de orientarte para que luego consultes a tu medico. Comencemos a hacer una evaluacion.
        '''</summary>
        Friend Shared ReadOnly Property mensajeinicial() As String
            Get
                Return ResourceManager.GetString("mensajeinicial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No.
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No existen patologias con los sintomas que has ingresado !, puedes iniciar sesion con un medico para consultar.
        '''</summary>
        Friend Shared ReadOnly Property noexistenpatologias() As String
            Get
                Return ResourceManager.GetString("noexistenpatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nueva Consulta.
        '''</summary>
        Friend Shared ReadOnly Property nuevaconsulta() As String
            Get
                Return ResourceManager.GetString("nuevaconsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a N`.
        '''</summary>
        Friend Shared ReadOnly Property numero() As String
            Get
                Return ResourceManager.GetString("numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En Linea.
        '''</summary>
        Friend Shared ReadOnly Property online() As String
            Get
                Return ResourceManager.GetString("online", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologias diagnosticadas.
        '''</summary>
        Friend Shared ReadOnly Property patologiasdiagnosticadas() As String
            Get
                Return ResourceManager.GetString("patologiasdiagnosticadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologias pre-existentes.
        '''</summary>
        Friend Shared ReadOnly Property patologiaspreexistentes() As String
            Get
                Return ResourceManager.GetString("patologiaspreexistentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Presiona Ver Informe para que podamos generarte un diagnostico de acuerdo a los sintomas que has ingresado. No dejes de consultara tu medico via chat, recuerda que este diagnostico no sustituye la consulta a un profesional..
        '''</summary>
        Friend Shared ReadOnly Property presionaparaverinforme() As String
            Get
                Return ResourceManager.GetString("presionaparaverinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Que otro sintoma tienes, ingresalo....
        '''</summary>
        Friend Shared ReadOnly Property queotrosintomatienes() As String
            Get
                Return ResourceManager.GetString("queotrosintomatienes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recordar mis datos.
        '''</summary>
        Friend Shared ReadOnly Property recordarmisdatos() As String
            Get
                Return ResourceManager.GetString("recordarmisdatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Saber mas....
        '''</summary>
        Friend Shared ReadOnly Property sabermas() As String
            Get
                Return ResourceManager.GetString("sabermas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estas seguro de cerrar la aplicacion?.
        '''</summary>
        Friend Shared ReadOnly Property segurocerraraplicacion() As String
            Get
                Return ResourceManager.GetString("segurocerraraplicacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seguro de cerrar la sesion de chat?.
        '''</summary>
        Friend Shared ReadOnly Property segurocerrarsesion() As String
            Get
                Return ResourceManager.GetString("segurocerrarsesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Si.
        '''</summary>
        Friend Shared ReadOnly Property si() As String
            Get
                Return ResourceManager.GetString("si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sientes otro sintoma?, ingresalo....
        '''</summary>
        Friend Shared ReadOnly Property sientesotrosintoma() As String
            Get
                Return ResourceManager.GetString("sientesotrosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Siguientes.
        '''</summary>
        Friend Shared ReadOnly Property siguiente() As String
            Get
                Return ResourceManager.GetString("siguiente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Si tienes otro sintoma, ingresalo....
        '''</summary>
        Friend Shared ReadOnly Property sitienesotrosintoma() As String
            Get
                Return ResourceManager.GetString("sitienesotrosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Telefonos.
        '''</summary>
        Friend Shared ReadOnly Property telefonos() As String
            Get
                Return ResourceManager.GetString("telefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tienes otro sintoma, ingresalo....
        '''</summary>
        Friend Shared ReadOnly Property tienesotrosintoma() As String
            Get
                Return ResourceManager.GetString("tienesotrosintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tu.
        '''</summary>
        Friend Shared ReadOnly Property tu() As String
            Get
                Return ResourceManager.GetString("tu", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario Registrado.
        '''</summary>
        Friend Shared ReadOnly Property usuarioregistrado() As String
            Get
                Return ResourceManager.GetString("usuarioregistrado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Datos personales.
        '''</summary>
        Friend Shared ReadOnly Property verificarinformacionpersonal() As String
            Get
                Return ResourceManager.GetString("verificarinformacionpersonal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver Informe.
        '''</summary>
        Friend Shared ReadOnly Property verinforme() As String
            Get
                Return ResourceManager.GetString("verinforme", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
