'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("appGestion.en", GetType(en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a April.
        '''</summary>
        Friend Shared ReadOnly Property abril() As String
            Get
                Return ResourceManager.GetString("abril", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a About.
        '''</summary>
        Friend Shared ReadOnly Property acercade() As String
            Get
                Return ResourceManager.GetString("acercade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Active.
        '''</summary>
        Friend Shared ReadOnly Property activo() As String
            Get
                Return ResourceManager.GetString("activo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrative.
        '''</summary>
        Friend Shared ReadOnly Property administrativo() As String
            Get
                Return ResourceManager.GetString("administrativo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrative.
        '''</summary>
        Friend Shared ReadOnly Property administrativos() As String
            Get
                Return ResourceManager.GetString("administrativos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a August.
        '''</summary>
        Friend Shared ReadOnly Property agosto() As String
            Get
                Return ResourceManager.GetString("agosto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Add.
        '''</summary>
        Friend Shared ReadOnly Property agregar() As String
            Get
                Return ResourceManager.GetString("agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This change requires a reboot system, are you sure?.
        '''</summary>
        Friend Shared ReadOnly Property alertacambioidioma() As String
            Get
                Return ResourceManager.GetString("alertacambioidioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Something in the configuration is not right, check.
        '''</summary>
        Friend Shared ReadOnly Property algoenlaconfiguracionnoestabien() As String
            Get
                Return ResourceManager.GetString("algoenlaconfiguracionnoestabien", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Year.
        '''</summary>
        Friend Shared ReadOnly Property ano() As String
            Get
                Return ResourceManager.GetString("ano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LAST NAME.
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Apply.
        '''</summary>
        Friend Shared ReadOnly Property aplicar() As String
            Get
                Return ResourceManager.GetString("aplicar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SUIT.
        '''</summary>
        Friend Shared ReadOnly Property apto() As String
            Get
                Return ResourceManager.GetString("apto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Notice.
        '''</summary>
        Friend Shared ReadOnly Property aviso() As String
            Get
                Return ResourceManager.GetString("aviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirm action.
        '''</summary>
        Friend Shared ReadOnly Property avisoalerta() As String
            Get
                Return ResourceManager.GetString("avisoalerta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property avisoerror() As String
            Get
                Return ResourceManager.GetString("avisoerror", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Help.
        '''</summary>
        Friend Shared ReadOnly Property ayuda() As String
            Get
                Return ResourceManager.GetString("ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOCATION.
        '''</summary>
        Friend Shared ReadOnly Property barrio() As String
            Get
                Return ResourceManager.GetString("barrio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete.
        '''</summary>
        Friend Shared ReadOnly Property borrar() As String
            Get
                Return ResourceManager.GetString("borrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Look for.
        '''</summary>
        Friend Shared ReadOnly Property buscar() As String
            Get
                Return ResourceManager.GetString("buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search.
        '''</summary>
        Friend Shared ReadOnly Property busqueda() As String
            Get
                Return ResourceManager.GetString("busqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change of password.
        '''</summary>
        Friend Shared ReadOnly Property cambiopass() As String
            Get
                Return ResourceManager.GetString("cambiopass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed change password.
        '''</summary>
        Friend Shared ReadOnly Property cambiopasswordfailed() As String
            Get
                Return ResourceManager.GetString("cambiopasswordfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Successful password change.
        '''</summary>
        Friend Shared ReadOnly Property cambiopasswordsuccess() As String
            Get
                Return ResourceManager.GetString("cambiopasswordsuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Quantity.
        '''</summary>
        Friend Shared ReadOnly Property cantidad() As String
            Get
                Return ResourceManager.GetString("cantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Amount of chat made.
        '''</summary>
        Friend Shared ReadOnly Property cantidadchatrealizados() As String
            Get
                Return ResourceManager.GetString("cantidadchatrealizados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number of Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property cantidaddesintomas() As String
            Get
                Return ResourceManager.GetString("cantidaddesintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The number of symptoms is incorrect, check ....
        '''</summary>
        Friend Shared ReadOnly Property cantidaddesintomasincorrecta() As String
            Get
                Return ResourceManager.GetString("cantidaddesintomasincorrecta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Number of diagnoses received.
        '''</summary>
        Friend Shared ReadOnly Property cantidaddiagnosticosrecibidos() As String
            Get
                Return ResourceManager.GetString("cantidaddiagnosticosrecibidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Close.
        '''</summary>
        Friend Shared ReadOnly Property cerrar() As String
            Get
                Return ResourceManager.GetString("cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat.
        '''</summary>
        Friend Shared ReadOnly Property chat() As String
            Get
                Return ResourceManager.GetString("chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chats.
        '''</summary>
        Friend Shared ReadOnly Property chats() As String
            Get
                Return ResourceManager.GetString("chats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connections.
        '''</summary>
        Friend Shared ReadOnly Property conexiones() As String
            Get
                Return ResourceManager.GetString("conexiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Setting.
        '''</summary>
        Friend Shared ReadOnly Property configuracion() As String
            Get
                Return ResourceManager.GetString("configuracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Configure Email.
        '''</summary>
        Friend Shared ReadOnly Property configuraremail() As String
            Get
                Return ResourceManager.GetString("configuraremail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirm.
        '''</summary>
        Friend Shared ReadOnly Property confirmar() As String
            Get
                Return ResourceManager.GetString("confirmar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure to reactivate the account?.
        '''</summary>
        Friend Shared ReadOnly Property confirmarreactivarregistro() As String
            Get
                Return ResourceManager.GetString("confirmarreactivarregistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Credential.
        '''</summary>
        Friend Shared ReadOnly Property credencial() As String
            Get
                Return ResourceManager.GetString("credencial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Data.
        '''</summary>
        Friend Shared ReadOnly Property datos() As String
            Get
                Return ResourceManager.GetString("datos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email data.
        '''</summary>
        Friend Shared ReadOnly Property datosemail() As String
            Get
                Return ResourceManager.GetString("datosemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Statistical data.
        '''</summary>
        Friend Shared ReadOnly Property datosestadisticos() As String
            Get
                Return ResourceManager.GetString("datosestadisticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save success.
        '''</summary>
        Friend Shared ReadOnly Property datosguardadosconexito() As String
            Get
                Return ResourceManager.GetString("datosguardadosconexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This option allows establishing the minimum number of symptoms that a patient must enter in order to receive a primary diagnosis..
        '''</summary>
        Friend Shared ReadOnly Property desccantidadsintomas() As String
            Get
                Return ResourceManager.GetString("desccantidadsintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System language, this change requires restarting the application..
        '''</summary>
        Friend Shared ReadOnly Property descidiomadelsistema() As String
            Get
                Return ResourceManager.GetString("descidiomadelsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property descripcion() As String
            Get
                Return ResourceManager.GetString("descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Destination.
        '''</summary>
        Friend Shared ReadOnly Property destino() As String
            Get
                Return ResourceManager.GetString("destino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticos() As String
            Get
                Return ResourceManager.GetString("diagnosticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnosis generated.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("diagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a December.
        '''</summary>
        Friend Shared ReadOnly Property diciembre() As String
            Get
                Return ResourceManager.GetString("diciembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ADDRESS.
        '''</summary>
        Friend Shared ReadOnly Property direccion() As String
            Get
                Return ResourceManager.GetString("direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Identification ID.
        '''</summary>
        Friend Shared ReadOnly Property docidentidad() As String
            Get
                Return ResourceManager.GetString("docidentidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IDENTIFICATION.
        '''</summary>
        Friend Shared ReadOnly Property documento() As String
            Get
                Return ResourceManager.GetString("documento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The document already exists. Verify document.
        '''</summary>
        Friend Shared ReadOnly Property documentoexiste() As String
            Get
                Return ResourceManager.GetString("documentoexiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The symptom already exists.
        '''</summary>
        Friend Shared ReadOnly Property elsistomayaexiste() As String
            Get
                Return ResourceManager.GetString("elsistomayaexiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a EMAIL.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contact email.
        '''</summary>
        Friend Shared ReadOnly Property emaildecontacto() As String
            Get
                Return ResourceManager.GetString("emaildecontacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Emergency.
        '''</summary>
        Friend Shared ReadOnly Property emergencia() As String
            Get
                Return ResourceManager.GetString("emergencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a English.
        '''</summary>
        Friend Shared ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a January.
        '''</summary>
        Friend Shared ReadOnly Property enero() As String
            Get
                Return ResourceManager.GetString("enero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diseases.
        '''</summary>
        Friend Shared ReadOnly Property enfermedades() As String
            Get
                Return ResourceManager.GetString("enfermedades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Access error.
        '''</summary>
        Friend Shared ReadOnly Property erroracceso() As String
            Get
                Return ResourceManager.GetString("erroracceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save failed.
        '''</summary>
        Friend Shared ReadOnly Property erroralguardardatos() As String
            Get
                Return ResourceManager.GetString("erroralguardardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The configuration file cannot be found. Can&apos;t continue.
        '''</summary>
        Friend Shared ReadOnly Property errorarchivo() As String
            Get
                Return ResourceManager.GetString("errorarchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to delete record.
        '''</summary>
        Friend Shared ReadOnly Property errorborrarregistro() As String
            Get
                Return ResourceManager.GetString("errorborrarregistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error trying to delete user.
        '''</summary>
        Friend Shared ReadOnly Property errorborrarusuario() As String
            Get
                Return ResourceManager.GetString("errorborrarusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There is an error in the configuration, it could not be saved. Check.
        '''</summary>
        Friend Shared ReadOnly Property errorconfiguracion() As String
            Get
                Return ResourceManager.GetString("errorconfiguracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error creating user in database.
        '''</summary>
        Friend Shared ReadOnly Property errorcrearusuario() As String
            Get
                Return ResourceManager.GetString("errorcrearusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error exporting data.
        '''</summary>
        Friend Shared ReadOnly Property errorexportardatos() As String
            Get
                Return ResourceManager.GetString("errorexportardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to retrieve data.
        '''</summary>
        Friend Shared ReadOnly Property errorrecuperardatos() As String
            Get
                Return ResourceManager.GetString("errorrecuperardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Failed to verify the document.
        '''</summary>
        Friend Shared ReadOnly Property errorverificardocumento() As String
            Get
                Return ResourceManager.GetString("errorverificardocumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Spanish.
        '''</summary>
        Friend Shared ReadOnly Property es() As String
            Get
                Return ResourceManager.GetString("es", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CORNER.
        '''</summary>
        Friend Shared ReadOnly Property esquina() As String
            Get
                Return ResourceManager.GetString("esquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Export to BD.
        '''</summary>
        Friend Shared ReadOnly Property exportarabasededatos() As String
            Get
                Return ResourceManager.GetString("exportarabasededatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Missing data to import.
        '''</summary>
        Friend Shared ReadOnly Property faltandatosarapoderimportar() As String
            Get
                Return ResourceManager.GetString("faltandatosarapoderimportar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Required data is missing, check ....
        '''</summary>
        Friend Shared ReadOnly Property faltandatosrequeridos() As String
            Get
                Return ResourceManager.GetString("faltandatosrequeridos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a February.
        '''</summary>
        Friend Shared ReadOnly Property febrero() As String
            Get
                Return ResourceManager.GetString("febrero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DATE.
        '''</summary>
        Friend Shared ReadOnly Property fecha() As String
            Get
                Return ResourceManager.GetString("fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a BIRTHDAY.
        '''</summary>
        Friend Shared ReadOnly Property fechanacimiento() As String
            Get
                Return ResourceManager.GetString("fechanacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wrong format to import.
        '''</summary>
        Friend Shared ReadOnly Property formatoincorrectoparaimportar() As String
            Get
                Return ResourceManager.GetString("formatoincorrectoparaimportar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save.
        '''</summary>
        Friend Shared ReadOnly Property guardar() As String
            Get
                Return ResourceManager.GetString("guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enabled.
        '''</summary>
        Friend Shared ReadOnly Property habilitado() As String
            Get
                Return ResourceManager.GetString("habilitado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a There are unsaved changes, do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property haycambiossinguardar() As String
            Get
                Return ResourceManager.GetString("haycambiossinguardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat history.
        '''</summary>
        Friend Shared ReadOnly Property historicodechats() As String
            Get
                Return ResourceManager.GetString("historicodechats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System Language.
        '''</summary>
        Friend Shared ReadOnly Property idiomasistema() As String
            Get
                Return ResourceManager.GetString("idiomasistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The data was imported successfully.
        '''</summary>
        Friend Shared ReadOnly Property importacionexitosa() As String
            Get
                Return ResourceManager.GetString("importacionexitosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Import data from CSV file.
        '''</summary>
        Friend Shared ReadOnly Property importarcsv() As String
            Get
                Return ResourceManager.GetString("importarcsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies Information.
        '''</summary>
        Friend Shared ReadOnly Property informacionpatologias() As String
            Get
                Return ResourceManager.GetString("informacionpatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chats Report.
        '''</summary>
        Friend Shared ReadOnly Property informechat() As String
            Get
                Return ResourceManager.GetString("informechat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generated Diagnostics Report.
        '''</summary>
        Friend Shared ReadOnly Property informediagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("informediagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reports.
        '''</summary>
        Friend Shared ReadOnly Property informes() As String
            Get
                Return ResourceManager.GetString("informes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnostics Report.
        '''</summary>
        Friend Shared ReadOnly Property informeuso() As String
            Get
                Return ResourceManager.GetString("informeuso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Login.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Admin IP Range.
        '''</summary>
        Friend Shared ReadOnly Property ipgestion() As String
            Get
                Return ResourceManager.GetString("ipgestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Medical IP Range.
        '''</summary>
        Friend Shared ReadOnly Property ipmedicos() As String
            Get
                Return ResourceManager.GetString("ipmedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IP Patients.
        '''</summary>
        Friend Shared ReadOnly Property ippacientes() As String
            Get
                Return ResourceManager.GetString("ippacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a July.
        '''</summary>
        Friend Shared ReadOnly Property julio() As String
            Get
                Return ResourceManager.GetString("julio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a June.
        '''</summary>
        Friend Shared ReadOnly Property junio() As String
            Get
                Return ResourceManager.GetString("junio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Language.
        '''</summary>
        Friend Shared ReadOnly Property lenguaje() As String
            Get
                Return ResourceManager.GetString("lenguaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrative List.
        '''</summary>
        Friend Shared ReadOnly Property listaadministrativos() As String
            Get
                Return ResourceManager.GetString("listaadministrativos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DOCTOR LIST.
        '''</summary>
        Friend Shared ReadOnly Property listademedicos() As String
            Get
                Return ResourceManager.GetString("listademedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctors List.
        '''</summary>
        Friend Shared ReadOnly Property listamedicos() As String
            Get
                Return ResourceManager.GetString("listamedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients List.
        '''</summary>
        Friend Shared ReadOnly Property listapacientes() As String
            Get
                Return ResourceManager.GetString("listapacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies List.
        '''</summary>
        Friend Shared ReadOnly Property listapatologias() As String
            Get
                Return ResourceManager.GetString("listapatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a List all.
        '''</summary>
        Friend Shared ReadOnly Property listartodos() As String
            Get
                Return ResourceManager.GetString("listartodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms List.
        '''</summary>
        Friend Shared ReadOnly Property listasintomas() As String
            Get
                Return ResourceManager.GetString("listasintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Incorrect ID or password, please verify.
        '''</summary>
        Friend Shared ReadOnly Property loginincorrecto() As String
            Get
                Return ResourceManager.GetString("loginincorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a System log.
        '''</summary>
        Friend Shared ReadOnly Property logsistema() As String
            Get
                Return ResourceManager.GetString("logsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a March.
        '''</summary>
        Friend Shared ReadOnly Property marzo() As String
            Get
                Return ResourceManager.GetString("marzo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a May.
        '''</summary>
        Friend Shared ReadOnly Property mayo() As String
            Get
                Return ResourceManager.GetString("mayo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctor.
        '''</summary>
        Friend Shared ReadOnly Property medico() As String
            Get
                Return ResourceManager.GetString("medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctors.
        '''</summary>
        Friend Shared ReadOnly Property medicos() As String
            Get
                Return ResourceManager.GetString("medicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Month.
        '''</summary>
        Friend Shared ReadOnly Property mes() As String
            Get
                Return ResourceManager.GetString("mes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Consultation Month and Year.
        '''</summary>
        Friend Shared ReadOnly Property mesanoconsulta() As String
            Get
                Return ResourceManager.GetString("mesanoconsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Months.
        '''</summary>
        Friend Shared ReadOnly Property meses() As String
            Get
                Return ResourceManager.GetString("meses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modific.
        '''</summary>
        Friend Shared ReadOnly Property modificar() As String
            Get
                Return ResourceManager.GetString("modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No.
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NAMES.
        '''</summary>
        Friend Shared ReadOnly Property nombres() As String
            Get
                Return ResourceManager.GetString("nombres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a November.
        '''</summary>
        Friend Shared ReadOnly Property noviembre() As String
            Get
                Return ResourceManager.GetString("noviembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New.
        '''</summary>
        Friend Shared ReadOnly Property nueva() As String
            Get
                Return ResourceManager.GetString("nueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a New Password.
        '''</summary>
        Friend Shared ReadOnly Property nuevopassword() As String
            Get
                Return ResourceManager.GetString("nuevopassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº:.
        '''</summary>
        Friend Shared ReadOnly Property numero() As String
            Get
                Return ResourceManager.GetString("numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a EMPLOYEE ID.
        '''</summary>
        Friend Shared ReadOnly Property numeroempelado() As String
            Get
                Return ResourceManager.GetString("numeroempelado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº DOCTOR.
        '''</summary>
        Friend Shared ReadOnly Property numeromedico() As String
            Get
                Return ResourceManager.GetString("numeromedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a October.
        '''</summary>
        Friend Shared ReadOnly Property octubre() As String
            Get
                Return ResourceManager.GetString("octubre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Allows the entry of a new phone.
        '''</summary>
        Friend Shared ReadOnly Property opcionagregartelefono() As String
            Get
                Return ResourceManager.GetString("opcionagregartelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Delete the selected phone in the list.
        '''</summary>
        Friend Shared ReadOnly Property opcioneliminartelefono() As String
            Get
                Return ResourceManager.GetString("opcioneliminartelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone options.
        '''</summary>
        Friend Shared ReadOnly Property opcionestelefonos() As String
            Get
                Return ResourceManager.GetString("opcionestelefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Origin and Destination.
        '''</summary>
        Friend Shared ReadOnly Property origendestino() As String
            Get
                Return ResourceManager.GetString("origendestino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Other data.
        '''</summary>
        Friend Shared ReadOnly Property otrosdatos() As String
            Get
                Return ResourceManager.GetString("otrosdatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patient.
        '''</summary>
        Friend Shared ReadOnly Property paciente() As String
            Get
                Return ResourceManager.GetString("paciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patients.
        '''</summary>
        Friend Shared ReadOnly Property pacientes() As String
            Get
                Return ResourceManager.GetString("pacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Parameters.
        '''</summary>
        Friend Shared ReadOnly Property parametros() As String
            Get
                Return ResourceManager.GetString("parametros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathology reactivated successfully.
        '''</summary>
        Friend Shared ReadOnly Property patologiareactivadaconexito() As String
            Get
                Return ResourceManager.GetString("patologiareactivadaconexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies.
        '''</summary>
        Friend Shared ReadOnly Property patologias() As String
            Get
                Return ResourceManager.GetString("patologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Most diagnosed pathologies, last 12 months.
        '''</summary>
        Friend Shared ReadOnly Property patologiasdiagnosticadas() As String
            Get
                Return ResourceManager.GetString("patologiasdiagnosticadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies by symptoms.
        '''</summary>
        Friend Shared ReadOnly Property patologiasporsintoma() As String
            Get
                Return ResourceManager.GetString("patologiasporsintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Weighing.
        '''</summary>
        Friend Shared ReadOnly Property ponderacion() As String
            Get
                Return ResourceManager.GetString("ponderacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pre-existing.
        '''</summary>
        Friend Shared ReadOnly Property preexistentes() As String
            Get
                Return ResourceManager.GetString("preexistentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SMTP port.
        '''</summary>
        Friend Shared ReadOnly Property puertosmtp() As String
            Get
                Return ResourceManager.GetString("puertosmtp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ranking of pathologies.
        '''</summary>
        Friend Shared ReadOnly Property rankingdepatologias() As String
            Get
                Return ResourceManager.GetString("rankingdepatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reactivate.
        '''</summary>
        Friend Shared ReadOnly Property reactivar() As String
            Get
                Return ResourceManager.GetString("reactivar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recover.
        '''</summary>
        Friend Shared ReadOnly Property recuperar() As String
            Get
                Return ResourceManager.GetString("recuperar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registry removed successfully!.
        '''</summary>
        Friend Shared ReadOnly Property registroeleminado() As String
            Get
                Return ResourceManager.GetString("registroeleminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Historical records.
        '''</summary>
        Friend Shared ReadOnly Property registroshistoricos() As String
            Get
                Return ResourceManager.GetString("registroshistoricos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rewrite password.
        '''</summary>
        Friend Shared ReadOnly Property renuevopassword() As String
            Get
                Return ResourceManager.GetString("renuevopassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Exit.
        '''</summary>
        Friend Shared ReadOnly Property salir() As String
            Get
                Return ResourceManager.GetString("salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a The configuration was saved successfully.
        '''</summary>
        Friend Shared ReadOnly Property seguardolaconfiguracion() As String
            Get
                Return ResourceManager.GetString("seguardolaconfiguracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure to delete the record?.
        '''</summary>
        Friend Shared ReadOnly Property segurodeeliminiar() As String
            Get
                Return ResourceManager.GetString("segurodeeliminiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Are you sure to reactivate the pathology?.
        '''</summary>
        Friend Shared ReadOnly Property segurodereactivarpatologia() As String
            Get
                Return ResourceManager.GetString("segurodereactivarpatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select the report.
        '''</summary>
        Friend Shared ReadOnly Property seleccionaelinforme() As String
            Get
                Return ResourceManager.GetString("seleccionaelinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SMTP server.
        '''</summary>
        Friend Shared ReadOnly Property servidorsmtp() As String
            Get
                Return ResourceManager.GetString("servidorsmtp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Session.
        '''</summary>
        Friend Shared ReadOnly Property sesion() As String
            Get
                Return ResourceManager.GetString("sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a September.
        '''</summary>
        Friend Shared ReadOnly Property setiembre() As String
            Get
                Return ResourceManager.GetString("setiembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Yes.
        '''</summary>
        Friend Shared ReadOnly Property si() As String
            Get
                Return ResourceManager.GetString("si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property sintomas() As String
            Get
                Return ResourceManager.GetString("sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Without urgency.
        '''</summary>
        Friend Shared ReadOnly Property sinurgencia() As String
            Get
                Return ResourceManager.GetString("sinurgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Software de Gestion Medica.
        '''</summary>
        Friend Shared ReadOnly Property softwaregestionmedica() As String
            Get
                Return ResourceManager.GetString("softwaregestionmedica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Only active.
        '''</summary>
        Friend Shared ReadOnly Property soloactivos() As String
            Get
                Return ResourceManager.GetString("soloactivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Only inactive.
        '''</summary>
        Friend Shared ReadOnly Property soloinactivos() As String
            Get
                Return ResourceManager.GetString("soloinactivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnostic report generated in the last 12 mobile months.
        '''</summary>
        Friend Shared ReadOnly Property subitutlodiagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("subitutlodiagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minimum number of symptoms that a patient must indicate to receive a diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property subsitulosintomas() As String
            Get
                Return ResourceManager.GetString("subsitulosintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Connection IP address configuration for different applications.
        '''</summary>
        Friend Shared ReadOnly Property subtituloconexiones() As String
            Get
                Return ResourceManager.GetString("subtituloconexiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save the necessary configuration for sending Email from the medical app.
        '''</summary>
        Friend Shared ReadOnly Property subtituloemail() As String
            Get
                Return ResourceManager.GetString("subtituloemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat generated in the required month.
        '''</summary>
        Friend Shared ReadOnly Property subtituloinfochatmes() As String
            Get
                Return ResourceManager.GetString("subtituloinfochatmes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat registered in the last 12 mobile months.
        '''</summary>
        Friend Shared ReadOnly Property subtituloinfochatmeses() As String
            Get
                Return ResourceManager.GetString("subtituloinfochatmeses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phones.
        '''</summary>
        Friend Shared ReadOnly Property telefonos() As String
            Get
                Return ResourceManager.GetString("telefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generated Chat.
        '''</summary>
        Friend Shared ReadOnly Property tituloinfochat() As String
            Get
                Return ResourceManager.GetString("tituloinfochat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enables the entry of a new record.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonagregar() As String
            Get
                Return ResourceManager.GetString("toolbotonagregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Clear on-screen log.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonborrar() As String
            Get
                Return ResourceManager.GetString("toolbotonborrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Search by.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonbuscar() As String
            Get
                Return ResourceManager.GetString("toolbotonbuscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancel changes.
        '''</summary>
        Friend Shared ReadOnly Property toolbotoncancelar() As String
            Get
                Return ResourceManager.GetString("toolbotoncancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Save Changes.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonguardar() As String
            Get
                Return ResourceManager.GetString("toolbotonguardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enable modification.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonmodificar() As String
            Get
                Return ResourceManager.GetString("toolbotonmodificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Start a new search.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonnueva() As String
            Get
                Return ResourceManager.GetString("toolbotonnueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reactivate account on screen.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonreactivar() As String
            Get
                Return ResourceManager.GetString("toolbotonreactivar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Urgency.
        '''</summary>
        Friend Shared ReadOnly Property urgencia() As String
            Get
                Return ResourceManager.GetString("urgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Minor Urgency.
        '''</summary>
        Friend Shared ReadOnly Property urgenciamenor() As String
            Get
                Return ResourceManager.GetString("urgenciamenor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a User.
        '''</summary>
        Friend Shared ReadOnly Property usuario() As String
            Get
                Return ResourceManager.GetString("usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Account has been successfully activated.
        '''</summary>
        Friend Shared ReadOnly Property usuariorestauradoexito() As String
            Get
                Return ResourceManager.GetString("usuariorestauradoexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a View Chat.
        '''</summary>
        Friend Shared ReadOnly Property verchat() As String
            Get
                Return ResourceManager.GetString("verchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a View reports.
        '''</summary>
        Friend Shared ReadOnly Property verinformes() As String
            Get
                Return ResourceManager.GetString("verinformes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a See Doctor.
        '''</summary>
        Friend Shared ReadOnly Property verMedico() As String
            Get
                Return ResourceManager.GetString("verMedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a See Pathology.
        '''</summary>
        Friend Shared ReadOnly Property verpatologia() As String
            Get
                Return ResourceManager.GetString("verpatologia", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
