'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class en
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("appGestion.en", GetType(en).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to April.
        '''</summary>
        Friend Shared ReadOnly Property abril() As String
            Get
                Return ResourceManager.GetString("abril", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Action.
        '''</summary>
        Friend Shared ReadOnly Property accion() As String
            Get
                Return ResourceManager.GetString("accion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property acercade() As String
            Get
                Return ResourceManager.GetString("acercade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activate.
        '''</summary>
        Friend Shared ReadOnly Property activar() As String
            Get
                Return ResourceManager.GetString("activar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activity.
        '''</summary>
        Friend Shared ReadOnly Property actividad() As String
            Get
                Return ResourceManager.GetString("actividad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Activity last 12 mobile months.
        '''</summary>
        Friend Shared ReadOnly Property actividaddoceMeses() As String
            Get
                Return ResourceManager.GetString("actividaddoceMeses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Active.
        '''</summary>
        Friend Shared ReadOnly Property activo() As String
            Get
                Return ResourceManager.GetString("activo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrative.
        '''</summary>
        Friend Shared ReadOnly Property administrativo() As String
            Get
                Return ResourceManager.GetString("administrativo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrative.
        '''</summary>
        Friend Shared ReadOnly Property administrativos() As String
            Get
                Return ResourceManager.GetString("administrativos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to August.
        '''</summary>
        Friend Shared ReadOnly Property agosto() As String
            Get
                Return ResourceManager.GetString("agosto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Add.
        '''</summary>
        Friend Shared ReadOnly Property agregar() As String
            Get
                Return ResourceManager.GetString("agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This change requires restarting the application. Are you sure you want to apply the previous changes?.
        '''</summary>
        Friend Shared ReadOnly Property alertacambioidioma() As String
            Get
                Return ResourceManager.GetString("alertacambioidioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Something went wrong ! Please try again.
        '''</summary>
        Friend Shared ReadOnly Property algoenlaconfiguracionnoestabien() As String
            Get
                Return ResourceManager.GetString("algoenlaconfiguracionnoestabien", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Year.
        '''</summary>
        Friend Shared ReadOnly Property ano() As String
            Get
                Return ResourceManager.GetString("ano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Surname .
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Apply.
        '''</summary>
        Friend Shared ReadOnly Property aplicar() As String
            Get
                Return ResourceManager.GetString("aplicar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SUIT.
        '''</summary>
        Friend Shared ReadOnly Property apto() As String
            Get
                Return ResourceManager.GetString("apto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to [Vida Sana] New credentials.
        '''</summary>
        Friend Shared ReadOnly Property asuntoaltacuenta() As String
            Get
                Return ResourceManager.GetString("asuntoaltacuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Notification.
        '''</summary>
        Friend Shared ReadOnly Property aviso() As String
            Get
                Return ResourceManager.GetString("aviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning.
        '''</summary>
        Friend Shared ReadOnly Property avisoalerta() As String
            Get
                Return ResourceManager.GetString("avisoalerta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property avisoerror() As String
            Get
                Return ResourceManager.GetString("avisoerror", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property ayuda() As String
            Get
                Return ResourceManager.GetString("ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to LOCATION.
        '''</summary>
        Friend Shared ReadOnly Property barrio() As String
            Get
                Return ResourceManager.GetString("barrio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DataBase.
        '''</summary>
        Friend Shared ReadOnly Property basededatos() As String
            Get
                Return ResourceManager.GetString("basededatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete.
        '''</summary>
        Friend Shared ReadOnly Property borrar() As String
            Get
                Return ResourceManager.GetString("borrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Good news.
        '''</summary>
        Friend Shared ReadOnly Property buenasnoticias() As String
            Get
                Return ResourceManager.GetString("buenasnoticias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property buscar() As String
            Get
                Return ResourceManager.GetString("buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search.
        '''</summary>
        Friend Shared ReadOnly Property busqueda() As String
            Get
                Return ResourceManager.GetString("busqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change password.
        '''</summary>
        Friend Shared ReadOnly Property cambiopass() As String
            Get
                Return ResourceManager.GetString("cambiopass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changing password Failed.
        '''</summary>
        Friend Shared ReadOnly Property cambiopasswordfailed() As String
            Get
                Return ResourceManager.GetString("cambiopasswordfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password has been changed successfully.
        '''</summary>
        Friend Shared ReadOnly Property cambiopasswordsuccess() As String
            Get
                Return ResourceManager.GetString("cambiopasswordsuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total.
        '''</summary>
        Friend Shared ReadOnly Property cantidad() As String
            Get
                Return ResourceManager.GetString("cantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Number of chat made .
        '''</summary>
        Friend Shared ReadOnly Property cantidadchatrealizados() As String
            Get
                Return ResourceManager.GetString("cantidadchatrealizados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total of Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property cantidaddesintomas() As String
            Get
                Return ResourceManager.GetString("cantidaddesintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The amount of symptoms entered is incorrect, please check and try again..
        '''</summary>
        Friend Shared ReadOnly Property cantidaddesintomasincorrecta() As String
            Get
                Return ResourceManager.GetString("cantidaddesintomasincorrecta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Total diagnoses received.
        '''</summary>
        Friend Shared ReadOnly Property cantidaddiagnosticosrecibidos() As String
            Get
                Return ResourceManager.GetString("cantidaddiagnosticosrecibidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Close.
        '''</summary>
        Friend Shared ReadOnly Property cerrar() As String
            Get
                Return ResourceManager.GetString("cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chat.
        '''</summary>
        Friend Shared ReadOnly Property chat() As String
            Get
                Return ResourceManager.GetString("chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chats.
        '''</summary>
        Friend Shared ReadOnly Property chats() As String
            Get
                Return ResourceManager.GetString("chats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connections.
        '''</summary>
        Friend Shared ReadOnly Property conexiones() As String
            Get
                Return ResourceManager.GetString("conexiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting.
        '''</summary>
        Friend Shared ReadOnly Property configuracion() As String
            Get
                Return ResourceManager.GetString("configuracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email config..
        '''</summary>
        Friend Shared ReadOnly Property configuraremail() As String
            Get
                Return ResourceManager.GetString("configuraremail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property confirmar() As String
            Get
                Return ResourceManager.GetString("confirmar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to reactivate this account?.
        '''</summary>
        Friend Shared ReadOnly Property confirmarreactivarregistro() As String
            Get
                Return ResourceManager.GetString("confirmarreactivarregistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Credential.
        '''</summary>
        Friend Shared ReadOnly Property credencial() As String
            Get
                Return ResourceManager.GetString("credencial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data.
        '''</summary>
        Friend Shared ReadOnly Property datos() As String
            Get
                Return ResourceManager.GetString("datos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email information .
        '''</summary>
        Friend Shared ReadOnly Property datosemail() As String
            Get
                Return ResourceManager.GetString("datosemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Statistics.
        '''</summary>
        Friend Shared ReadOnly Property datosestadisticos() As String
            Get
                Return ResourceManager.GetString("datosestadisticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Saved successfully.
        '''</summary>
        Friend Shared ReadOnly Property datosguardadosconexito() As String
            Get
                Return ResourceManager.GetString("datosguardadosconexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This option allow you to establish the minimum number of symptoms that a patient must entered in order to receive a primary diagnosis..
        '''</summary>
        Friend Shared ReadOnly Property desccantidadsintomas() As String
            Get
                Return ResourceManager.GetString("desccantidadsintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Aplication language, this change will require an application restart..
        '''</summary>
        Friend Shared ReadOnly Property descidiomadelsistema() As String
            Get
                Return ResourceManager.GetString("descidiomadelsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Description.
        '''</summary>
        Friend Shared ReadOnly Property descripcion() As String
            Get
                Return ResourceManager.GetString("descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to We have reset your password. These are your new access data:.
        '''</summary>
        Friend Shared ReadOnly Property descripcionrecuperacion() As String
            Get
                Return ResourceManager.GetString("descripcionrecuperacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Destination.
        '''</summary>
        Friend Shared ReadOnly Property destino() As String
            Get
                Return ResourceManager.GetString("destino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticos() As String
            Get
                Return ResourceManager.GetString("diagnosticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Given diagnoses.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("diagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to December.
        '''</summary>
        Friend Shared ReadOnly Property diciembre() As String
            Get
                Return ResourceManager.GetString("diciembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ADDRESS.
        '''</summary>
        Friend Shared ReadOnly Property direccion() As String
            Get
                Return ResourceManager.GetString("direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Id.
        '''</summary>
        Friend Shared ReadOnly Property docidentidad() As String
            Get
                Return ResourceManager.GetString("docidentidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Id.
        '''</summary>
        Friend Shared ReadOnly Property documento() As String
            Get
                Return ResourceManager.GetString("documento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to This document already exists. Please check again.
        '''</summary>
        Friend Shared ReadOnly Property documentoexiste() As String
            Get
                Return ResourceManager.GetString("documentoexiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mailing service is disabled.
        '''</summary>
        Friend Shared ReadOnly Property elenviodeemaildeshabilitado() As String
            Get
                Return ResourceManager.GetString("elenviodeemaildeshabilitado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The CDS Solution team.
        '''</summary>
        Friend Shared ReadOnly Property elquipode() As String
            Get
                Return ResourceManager.GetString("elquipode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The selected symptom already exists.
        '''</summary>
        Friend Shared ReadOnly Property elsistomayaexiste() As String
            Get
                Return ResourceManager.GetString("elsistomayaexiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMAIL.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Contact email.
        '''</summary>
        Friend Shared ReadOnly Property emaildecontacto() As String
            Get
                Return ResourceManager.GetString("emaildecontacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Email sent successfully.
        '''</summary>
        Friend Shared ReadOnly Property emailenviadocorrectamente() As String
            Get
                Return ResourceManager.GetString("emailenviadocorrectamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Emergency.
        '''</summary>
        Friend Shared ReadOnly Property emergencia() As String
            Get
                Return ResourceManager.GetString("emergencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to English.
        '''</summary>
        Friend Shared ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to January.
        '''</summary>
        Friend Shared ReadOnly Property enero() As String
            Get
                Return ResourceManager.GetString("enero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diseases.
        '''</summary>
        Friend Shared ReadOnly Property enfermedades() As String
            Get
                Return ResourceManager.GetString("enfermedades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Access error.
        '''</summary>
        Friend Shared ReadOnly Property erroracceso() As String
            Get
                Return ResourceManager.GetString("erroracceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cannot access to this file, it may be in use..
        '''</summary>
        Friend Shared ReadOnly Property erroraccesoarchivo() As String
            Get
                Return ResourceManager.GetString("erroraccesoarchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save failed.
        '''</summary>
        Friend Shared ReadOnly Property erroralguardardatos() As String
            Get
                Return ResourceManager.GetString("erroralguardardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Configuration file cannot be found. Can&apos;t continue.
        '''</summary>
        Friend Shared ReadOnly Property errorarchivo() As String
            Get
                Return ResourceManager.GetString("errorarchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record delete failed.
        '''</summary>
        Friend Shared ReadOnly Property errorborrarregistro() As String
            Get
                Return ResourceManager.GetString("errorborrarregistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User delete failed .
        '''</summary>
        Friend Shared ReadOnly Property errorborrarusuario() As String
            Get
                Return ResourceManager.GetString("errorborrarusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There was an issue trying to change the password.
        '''</summary>
        Friend Shared ReadOnly Property errorcambiarpassword() As String
            Get
                Return ResourceManager.GetString("errorcambiarpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There is an issue in the App configuration, the work in progress could not be saved. Please check and try again.
        '''</summary>
        Friend Shared ReadOnly Property errorconfiguracion() As String
            Get
                Return ResourceManager.GetString("errorconfiguracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User creation failed .
        '''</summary>
        Friend Shared ReadOnly Property errorcrearusuario() As String
            Get
                Return ResourceManager.GetString("errorcrearusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error when trying to send the mail.
        '''</summary>
        Friend Shared ReadOnly Property errorenviodeemail() As String
            Get
                Return ResourceManager.GetString("errorenviodeemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data export failed.
        '''</summary>
        Friend Shared ReadOnly Property errorexportardatos() As String
            Get
                Return ResourceManager.GetString("errorexportardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data recovery failed.
        '''</summary>
        Friend Shared ReadOnly Property errorrecuperardatos() As String
            Get
                Return ResourceManager.GetString("errorrecuperardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Document verification failed.
        '''</summary>
        Friend Shared ReadOnly Property errorverificardocumento() As String
            Get
                Return ResourceManager.GetString("errorverificardocumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Spanish.
        '''</summary>
        Friend Shared ReadOnly Property es() As String
            Get
                Return ResourceManager.GetString("es", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to STREET CORNER  .
        '''</summary>
        Friend Shared ReadOnly Property esquina() As String
            Get
                Return ResourceManager.GetString("esquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Export to DB&apos;s.
        '''</summary>
        Friend Shared ReadOnly Property exportarabasededatos() As String
            Get
                Return ResourceManager.GetString("exportarabasededatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Missing data to import.
        '''</summary>
        Friend Shared ReadOnly Property faltandatosarapoderimportar() As String
            Get
                Return ResourceManager.GetString("faltandatosarapoderimportar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Required data is missing, check ....
        '''</summary>
        Friend Shared ReadOnly Property faltandatosrequeridos() As String
            Get
                Return ResourceManager.GetString("faltandatosrequeridos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to February.
        '''</summary>
        Friend Shared ReadOnly Property febrero() As String
            Get
                Return ResourceManager.GetString("febrero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DATE.
        '''</summary>
        Friend Shared ReadOnly Property fecha() As String
            Get
                Return ResourceManager.GetString("fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to BIRTHDAY.
        '''</summary>
        Friend Shared ReadOnly Property fechanacimiento() As String
            Get
                Return ResourceManager.GetString("fechanacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Wrong format to import.
        '''</summary>
        Friend Shared ReadOnly Property formatoincorrectoparaimportar() As String
            Get
                Return ResourceManager.GetString("formatoincorrectoparaimportar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thanks for choosing us.
        '''</summary>
        Friend Shared ReadOnly Property graciasporpreferinos() As String
            Get
                Return ResourceManager.GetString("graciasporpreferinos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property guardar() As String
            Get
                Return ResourceManager.GetString("guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enabled.
        '''</summary>
        Friend Shared ReadOnly Property habilitado() As String
            Get
                Return ResourceManager.GetString("habilitado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to There are unsaved changes, do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property haycambiossinguardar() As String
            Get
                Return ResourceManager.GetString("haycambiossinguardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chat history.
        '''</summary>
        Friend Shared ReadOnly Property historicodechats() As String
            Get
                Return ResourceManager.GetString("historicodechats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Language.
        '''</summary>
        Friend Shared ReadOnly Property idiomasistema() As String
            Get
                Return ResourceManager.GetString("idiomasistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The data was imported successfully.
        '''</summary>
        Friend Shared ReadOnly Property importacionexitosa() As String
            Get
                Return ResourceManager.GetString("importacionexitosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Import data from CSV file.
        '''</summary>
        Friend Shared ReadOnly Property importarcsv() As String
            Get
                Return ResourceManager.GetString("importarcsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathologies Information.
        '''</summary>
        Friend Shared ReadOnly Property informacionpatologias() As String
            Get
                Return ResourceManager.GetString("informacionpatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chats Report.
        '''</summary>
        Friend Shared ReadOnly Property informechat() As String
            Get
                Return ResourceManager.GetString("informechat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generated Diagnostics Report.
        '''</summary>
        Friend Shared ReadOnly Property informediagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("informediagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reports.
        '''</summary>
        Friend Shared ReadOnly Property informes() As String
            Get
                Return ResourceManager.GetString("informes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnostics Report.
        '''</summary>
        Friend Shared ReadOnly Property informeuso() As String
            Get
                Return ResourceManager.GetString("informeuso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Login.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Admin IP Range.
        '''</summary>
        Friend Shared ReadOnly Property ipgestion() As String
            Get
                Return ResourceManager.GetString("ipgestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Medical IP Range.
        '''</summary>
        Friend Shared ReadOnly Property ipmedicos() As String
            Get
                Return ResourceManager.GetString("ipmedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to IP Patients.
        '''</summary>
        Friend Shared ReadOnly Property ippacientes() As String
            Get
                Return ResourceManager.GetString("ippacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to July.
        '''</summary>
        Friend Shared ReadOnly Property julio() As String
            Get
                Return ResourceManager.GetString("julio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to June.
        '''</summary>
        Friend Shared ReadOnly Property junio() As String
            Get
                Return ResourceManager.GetString("junio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property lenguaje() As String
            Get
                Return ResourceManager.GetString("lenguaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Administrative List.
        '''</summary>
        Friend Shared ReadOnly Property listaadministrativos() As String
            Get
                Return ResourceManager.GetString("listaadministrativos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to DOCTOR LIST.
        '''</summary>
        Friend Shared ReadOnly Property listademedicos() As String
            Get
                Return ResourceManager.GetString("listademedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doctors List.
        '''</summary>
        Friend Shared ReadOnly Property listamedicos() As String
            Get
                Return ResourceManager.GetString("listamedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patients List.
        '''</summary>
        Friend Shared ReadOnly Property listapacientes() As String
            Get
                Return ResourceManager.GetString("listapacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathologies List.
        '''</summary>
        Friend Shared ReadOnly Property listapatologias() As String
            Get
                Return ResourceManager.GetString("listapatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to List all.
        '''</summary>
        Friend Shared ReadOnly Property listartodos() As String
            Get
                Return ResourceManager.GetString("listartodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symptoms List.
        '''</summary>
        Friend Shared ReadOnly Property listasintomas() As String
            Get
                Return ResourceManager.GetString("listasintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Incorrect ID or password, please verify.
        '''</summary>
        Friend Shared ReadOnly Property loginincorrecto() As String
            Get
                Return ResourceManager.GetString("loginincorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System log.
        '''</summary>
        Friend Shared ReadOnly Property logsistema() As String
            Get
                Return ResourceManager.GetString("logsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to March.
        '''</summary>
        Friend Shared ReadOnly Property marzo() As String
            Get
                Return ResourceManager.GetString("marzo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to May.
        '''</summary>
        Friend Shared ReadOnly Property mayo() As String
            Get
                Return ResourceManager.GetString("mayo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doctor.
        '''</summary>
        Friend Shared ReadOnly Property medico() As String
            Get
                Return ResourceManager.GetString("medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Doctors.
        '''</summary>
        Friend Shared ReadOnly Property medicos() As String
            Get
                Return ResourceManager.GetString("medicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to You are going to generate a new password for the user, this change cannot be reversed, do you want to continue?.
        '''</summary>
        Friend Shared ReadOnly Property mensajerestablecerpassword() As String
            Get
                Return ResourceManager.GetString("mensajerestablecerpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Month.
        '''</summary>
        Friend Shared ReadOnly Property mes() As String
            Get
                Return ResourceManager.GetString("mes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Consultation Month and Year.
        '''</summary>
        Friend Shared ReadOnly Property mesanoconsulta() As String
            Get
                Return ResourceManager.GetString("mesanoconsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Months.
        '''</summary>
        Friend Shared ReadOnly Property meses() As String
            Get
                Return ResourceManager.GetString("meses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Modific.
        '''</summary>
        Friend Shared ReadOnly Property modificar() As String
            Get
                Return ResourceManager.GetString("modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Name.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to NAMES.
        '''</summary>
        Friend Shared ReadOnly Property nombres() As String
            Get
                Return ResourceManager.GetString("nombres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to November.
        '''</summary>
        Friend Shared ReadOnly Property noviembre() As String
            Get
                Return ResourceManager.GetString("noviembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New.
        '''</summary>
        Friend Shared ReadOnly Property nueva() As String
            Get
                Return ResourceManager.GetString("nueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New Password.
        '''</summary>
        Friend Shared ReadOnly Property nuevopassword() As String
            Get
                Return ResourceManager.GetString("nuevopassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nº:.
        '''</summary>
        Friend Shared ReadOnly Property numero() As String
            Get
                Return ResourceManager.GetString("numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to EMPLOYEE ID.
        '''</summary>
        Friend Shared ReadOnly Property numeroempelado() As String
            Get
                Return ResourceManager.GetString("numeroempelado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Nº DOCTOR.
        '''</summary>
        Friend Shared ReadOnly Property numeromedico() As String
            Get
                Return ResourceManager.GetString("numeromedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to October.
        '''</summary>
        Friend Shared ReadOnly Property octubre() As String
            Get
                Return ResourceManager.GetString("octubre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Allows the entry of a new phone.
        '''</summary>
        Friend Shared ReadOnly Property opcionagregartelefono() As String
            Get
                Return ResourceManager.GetString("opcionagregartelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete the selected phone in the list.
        '''</summary>
        Friend Shared ReadOnly Property opcioneliminartelefono() As String
            Get
                Return ResourceManager.GetString("opcioneliminartelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phone options.
        '''</summary>
        Friend Shared ReadOnly Property opcionestelefonos() As String
            Get
                Return ResourceManager.GetString("opcionestelefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Origin and Destination.
        '''</summary>
        Friend Shared ReadOnly Property origendestino() As String
            Get
                Return ResourceManager.GetString("origendestino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Other data.
        '''</summary>
        Friend Shared ReadOnly Property otrosdatos() As String
            Get
                Return ResourceManager.GetString("otrosdatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patient.
        '''</summary>
        Friend Shared ReadOnly Property paciente() As String
            Get
                Return ResourceManager.GetString("paciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Patients.
        '''</summary>
        Friend Shared ReadOnly Property pacientes() As String
            Get
                Return ResourceManager.GetString("pacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameters.
        '''</summary>
        Friend Shared ReadOnly Property parametros() As String
            Get
                Return ResourceManager.GetString("parametros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathology reactivated successfully.
        '''</summary>
        Friend Shared ReadOnly Property patologiareactivadaconexito() As String
            Get
                Return ResourceManager.GetString("patologiareactivadaconexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathologies.
        '''</summary>
        Friend Shared ReadOnly Property patologias() As String
            Get
                Return ResourceManager.GetString("patologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Most diagnosed pathologies, last 12 months.
        '''</summary>
        Friend Shared ReadOnly Property patologiasdiagnosticadas() As String
            Get
                Return ResourceManager.GetString("patologiasdiagnosticadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pathologies by symptoms.
        '''</summary>
        Friend Shared ReadOnly Property patologiasporsintoma() As String
            Get
                Return ResourceManager.GetString("patologiasporsintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Weighing.
        '''</summary>
        Friend Shared ReadOnly Property ponderacion() As String
            Get
                Return ResourceManager.GetString("ponderacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pre-existing.
        '''</summary>
        Friend Shared ReadOnly Property preexistentes() As String
            Get
                Return ResourceManager.GetString("preexistentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SMTP port.
        '''</summary>
        Friend Shared ReadOnly Property puertosmtp() As String
            Get
                Return ResourceManager.GetString("puertosmtp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ranking of pathologies.
        '''</summary>
        Friend Shared ReadOnly Property rankingdepatologias() As String
            Get
                Return ResourceManager.GetString("rankingdepatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to New password generation.
        '''</summary>
        Friend Shared ReadOnly Property recuperacionpassword() As String
            Get
                Return ResourceManager.GetString("recuperacionpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recover.
        '''</summary>
        Friend Shared ReadOnly Property recuperar() As String
            Get
                Return ResourceManager.GetString("recuperar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Registry removed successfully!.
        '''</summary>
        Friend Shared ReadOnly Property registroeleminado() As String
            Get
                Return ResourceManager.GetString("registroeleminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Historical records.
        '''</summary>
        Friend Shared ReadOnly Property registroshistoricos() As String
            Get
                Return ResourceManager.GetString("registroshistoricos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rewrite password.
        '''</summary>
        Friend Shared ReadOnly Property renuevopassword() As String
            Get
                Return ResourceManager.GetString("renuevopassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Recovery password.
        '''</summary>
        Friend Shared ReadOnly Property restablecerpassword() As String
            Get
                Return ResourceManager.GetString("restablecerpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property salir() As String
            Get
                Return ResourceManager.GetString("salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to The configuration was saved successfully.
        '''</summary>
        Friend Shared ReadOnly Property seguardolaconfiguracion() As String
            Get
                Return ResourceManager.GetString("seguardolaconfiguracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to delete the record?.
        '''</summary>
        Friend Shared ReadOnly Property segurodeeliminiar() As String
            Get
                Return ResourceManager.GetString("segurodeeliminiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure to reactivate the pathology?.
        '''</summary>
        Friend Shared ReadOnly Property segurodereactivarpatologia() As String
            Get
                Return ResourceManager.GetString("segurodereactivarpatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select the report.
        '''</summary>
        Friend Shared ReadOnly Property seleccionaelinforme() As String
            Get
                Return ResourceManager.GetString("seleccionaelinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Server.
        '''</summary>
        Friend Shared ReadOnly Property servidor() As String
            Get
                Return ResourceManager.GetString("servidor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to SMTP server.
        '''</summary>
        Friend Shared ReadOnly Property servidorsmtp() As String
            Get
                Return ResourceManager.GetString("servidorsmtp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Session.
        '''</summary>
        Friend Shared ReadOnly Property sesion() As String
            Get
                Return ResourceManager.GetString("sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sections.
        '''</summary>
        Friend Shared ReadOnly Property sesiones() As String
            Get
                Return ResourceManager.GetString("sesiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to September.
        '''</summary>
        Friend Shared ReadOnly Property setiembre() As String
            Get
                Return ResourceManager.GetString("setiembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property si() As String
            Get
                Return ResourceManager.GetString("si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symptoms.
        '''</summary>
        Friend Shared ReadOnly Property sintomas() As String
            Get
                Return ResourceManager.GetString("sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Symptoms never selected.
        '''</summary>
        Friend Shared ReadOnly Property sintomasnuncaseleccionados() As String
            Get
                Return ResourceManager.GetString("sintomasnuncaseleccionados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Without urgency.
        '''</summary>
        Friend Shared ReadOnly Property sinurgencia() As String
            Get
                Return ResourceManager.GetString("sinurgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Software de Gestion Medica.
        '''</summary>
        Friend Shared ReadOnly Property softwaregestionmedica() As String
            Get
                Return ResourceManager.GetString("softwaregestionmedica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only active.
        '''</summary>
        Friend Shared ReadOnly Property soloactivos() As String
            Get
                Return ResourceManager.GetString("soloactivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Only inactive.
        '''</summary>
        Friend Shared ReadOnly Property soloinactivos() As String
            Get
                Return ResourceManager.GetString("soloinactivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Diagnostic report generated in the last 12 mobile months.
        '''</summary>
        Friend Shared ReadOnly Property subitutlodiagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("subitutlodiagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minimum number of symptoms that a patient must indicate to receive a diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property subsitulosintomas() As String
            Get
                Return ResourceManager.GetString("subsitulosintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connection IP address configuration for different applications.
        '''</summary>
        Friend Shared ReadOnly Property subtituloconexiones() As String
            Get
                Return ResourceManager.GetString("subtituloconexiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save the necessary configuration for sending Email from the medical app.
        '''</summary>
        Friend Shared ReadOnly Property subtituloemail() As String
            Get
                Return ResourceManager.GetString("subtituloemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chat generated in the required month.
        '''</summary>
        Friend Shared ReadOnly Property subtituloinfochatmes() As String
            Get
                Return ResourceManager.GetString("subtituloinfochatmes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chat registered in the last 12 mobile months.
        '''</summary>
        Friend Shared ReadOnly Property subtituloinfochatmeses() As String
            Get
                Return ResourceManager.GetString("subtituloinfochatmeses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Displays the list of symptoms that patients never reported.
        '''</summary>
        Friend Shared ReadOnly Property subtitulolistasintomasnoseleccionados() As String
            Get
                Return ResourceManager.GetString("subtitulolistasintomasnoseleccionados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Phones.
        '''</summary>
        Friend Shared ReadOnly Property telefonos() As String
            Get
                Return ResourceManager.GetString("telefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Generated Chat.
        '''</summary>
        Friend Shared ReadOnly Property tituloinfochat() As String
            Get
                Return ResourceManager.GetString("tituloinfochat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Password recovery.
        '''</summary>
        Friend Shared ReadOnly Property titulorecuperarpassword() As String
            Get
                Return ResourceManager.GetString("titulorecuperarpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enables the entry of a new record.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonagregar() As String
            Get
                Return ResourceManager.GetString("toolbotonagregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear on-screen log.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonborrar() As String
            Get
                Return ResourceManager.GetString("toolbotonborrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search by.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonbuscar() As String
            Get
                Return ResourceManager.GetString("toolbotonbuscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel changes.
        '''</summary>
        Friend Shared ReadOnly Property toolbotoncancelar() As String
            Get
                Return ResourceManager.GetString("toolbotoncancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save Changes.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonguardar() As String
            Get
                Return ResourceManager.GetString("toolbotonguardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable modification.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonmodificar() As String
            Get
                Return ResourceManager.GetString("toolbotonmodificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Start a new search.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonnueva() As String
            Get
                Return ResourceManager.GetString("toolbotonnueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reactivate account on screen.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonreactivar() As String
            Get
                Return ResourceManager.GetString("toolbotonreactivar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Your account in Vida Sana has been activated, now you can enter the diagnostic application with the following information.
        '''</summary>
        Friend Shared ReadOnly Property tucuentaactivada() As String
            Get
                Return ResourceManager.GetString("tucuentaactivada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Urgency.
        '''</summary>
        Friend Shared ReadOnly Property urgencia() As String
            Get
                Return ResourceManager.GetString("urgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Minor Urgency.
        '''</summary>
        Friend Shared ReadOnly Property urgenciamenor() As String
            Get
                Return ResourceManager.GetString("urgenciamenor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to User.
        '''</summary>
        Friend Shared ReadOnly Property usuario() As String
            Get
                Return ResourceManager.GetString("usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Account has been successfully activated.
        '''</summary>
        Friend Shared ReadOnly Property usuariorestauradoexito() As String
            Get
                Return ResourceManager.GetString("usuariorestauradoexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View Chat.
        '''</summary>
        Friend Shared ReadOnly Property verchat() As String
            Get
                Return ResourceManager.GetString("verchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View reports.
        '''</summary>
        Friend Shared ReadOnly Property verinformes() As String
            Get
                Return ResourceManager.GetString("verinformes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to See Doctor.
        '''</summary>
        Friend Shared ReadOnly Property verMedico() As String
            Get
                Return ResourceManager.GetString("verMedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to See Pathology.
        '''</summary>
        Friend Shared ReadOnly Property verpatologia() As String
            Get
                Return ResourceManager.GetString("verpatologia", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
