'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class es
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("appGestion.es", GetType(es).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Abril.
        '''</summary>
        Friend Shared ReadOnly Property abril() As String
            Get
                Return ResourceManager.GetString("abril", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Accion.
        '''</summary>
        Friend Shared ReadOnly Property accion() As String
            Get
                Return ResourceManager.GetString("accion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Acerca de ....
        '''</summary>
        Friend Shared ReadOnly Property acercade() As String
            Get
                Return ResourceManager.GetString("acercade", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activar.
        '''</summary>
        Friend Shared ReadOnly Property Activar() As String
            Get
                Return ResourceManager.GetString("Activar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actividad.
        '''</summary>
        Friend Shared ReadOnly Property actividad() As String
            Get
                Return ResourceManager.GetString("actividad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Actividad ultimos 12 meses moviles.
        '''</summary>
        Friend Shared ReadOnly Property actividaddoceMeses() As String
            Get
                Return ResourceManager.GetString("actividaddoceMeses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activo.
        '''</summary>
        Friend Shared ReadOnly Property activo() As String
            Get
                Return ResourceManager.GetString("activo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrativo.
        '''</summary>
        Friend Shared ReadOnly Property administrativo() As String
            Get
                Return ResourceManager.GetString("administrativo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Administrativos.
        '''</summary>
        Friend Shared ReadOnly Property administrativos() As String
            Get
                Return ResourceManager.GetString("administrativos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agosto.
        '''</summary>
        Friend Shared ReadOnly Property agosto() As String
            Get
                Return ResourceManager.GetString("agosto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Agregar.
        '''</summary>
        Friend Shared ReadOnly Property agregar() As String
            Get
                Return ResourceManager.GetString("agregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Este cambio requiere reiniciar la aplicación, seguro de continuar?.
        '''</summary>
        Friend Shared ReadOnly Property alertacambioidioma() As String
            Get
                Return ResourceManager.GetString("alertacambioidioma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Algo en la configuracion de correo no esta bien, verifica....
        '''</summary>
        Friend Shared ReadOnly Property algoenlaconfiguracionnoestabien() As String
            Get
                Return ResourceManager.GetString("algoenlaconfiguracionnoestabien", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Año.
        '''</summary>
        Friend Shared ReadOnly Property ano() As String
            Get
                Return ResourceManager.GetString("ano", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a APELLIDOS.
        '''</summary>
        Friend Shared ReadOnly Property apellidos() As String
            Get
                Return ResourceManager.GetString("apellidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aplicar.
        '''</summary>
        Friend Shared ReadOnly Property aplicar() As String
            Get
                Return ResourceManager.GetString("aplicar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a APTO.
        '''</summary>
        Friend Shared ReadOnly Property apto() As String
            Get
                Return ResourceManager.GetString("apto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Activacion de cuenta en Vida Sana.
        '''</summary>
        Friend Shared ReadOnly Property asuntoaltacuenta() As String
            Get
                Return ResourceManager.GetString("asuntoaltacuenta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Aviso.
        '''</summary>
        Friend Shared ReadOnly Property aviso() As String
            Get
                Return ResourceManager.GetString("aviso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmación de Acción.
        '''</summary>
        Friend Shared ReadOnly Property avisoalerta() As String
            Get
                Return ResourceManager.GetString("avisoalerta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error.
        '''</summary>
        Friend Shared ReadOnly Property avisoerror() As String
            Get
                Return ResourceManager.GetString("avisoerror", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ayuda.
        '''</summary>
        Friend Shared ReadOnly Property ayuda() As String
            Get
                Return ResourceManager.GetString("ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a BARRIO.
        '''</summary>
        Friend Shared ReadOnly Property barrio() As String
            Get
                Return ResourceManager.GetString("barrio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Base de datos.
        '''</summary>
        Friend Shared ReadOnly Property basededatos() As String
            Get
                Return ResourceManager.GetString("basededatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Borrar.
        '''</summary>
        Friend Shared ReadOnly Property borrar() As String
            Get
                Return ResourceManager.GetString("borrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Buenas Noticias.
        '''</summary>
        Friend Shared ReadOnly Property buenasnoticias() As String
            Get
                Return ResourceManager.GetString("buenasnoticias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Buscar.
        '''</summary>
        Friend Shared ReadOnly Property buscar() As String
            Get
                Return ResourceManager.GetString("buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Búsqueda.
        '''</summary>
        Friend Shared ReadOnly Property busqueda() As String
            Get
                Return ResourceManager.GetString("busqueda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cambio de contraseña.
        '''</summary>
        Friend Shared ReadOnly Property cambiopass() As String
            Get
                Return ResourceManager.GetString("cambiopass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al cambiar la contraseña.
        '''</summary>
        Friend Shared ReadOnly Property cambiopasswordfailed() As String
            Get
                Return ResourceManager.GetString("cambiopasswordfailed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Se cambio correctamente la contraseña.
        '''</summary>
        Friend Shared ReadOnly Property cambiopasswordsuccess() As String
            Get
                Return ResourceManager.GetString("cambiopasswordsuccess", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancelar.
        '''</summary>
        Friend Shared ReadOnly Property cancelar() As String
            Get
                Return ResourceManager.GetString("cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cantidad.
        '''</summary>
        Friend Shared ReadOnly Property cantidad() As String
            Get
                Return ResourceManager.GetString("cantidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cantidad de chat realizados.
        '''</summary>
        Friend Shared ReadOnly Property cantidadchatrealizados() As String
            Get
                Return ResourceManager.GetString("cantidadchatrealizados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cantidad de síntomas.
        '''</summary>
        Friend Shared ReadOnly Property cantidaddesintomas() As String
            Get
                Return ResourceManager.GetString("cantidaddesintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La cantidad de sintomas es incorrecta, verifica....
        '''</summary>
        Friend Shared ReadOnly Property cantidaddesintomasincorrecta() As String
            Get
                Return ResourceManager.GetString("cantidaddesintomasincorrecta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cantidad de diagnósticos recibidos.
        '''</summary>
        Friend Shared ReadOnly Property cantidaddiagnosticosrecibidos() As String
            Get
                Return ResourceManager.GetString("cantidaddiagnosticosrecibidos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cerrar.
        '''</summary>
        Friend Shared ReadOnly Property cerrar() As String
            Get
                Return ResourceManager.GetString("cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat.
        '''</summary>
        Friend Shared ReadOnly Property chat() As String
            Get
                Return ResourceManager.GetString("chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chats.
        '''</summary>
        Friend Shared ReadOnly Property chats() As String
            Get
                Return ResourceManager.GetString("chats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Conexiones.
        '''</summary>
        Friend Shared ReadOnly Property conexiones() As String
            Get
                Return ResourceManager.GetString("conexiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Configuracion.
        '''</summary>
        Friend Shared ReadOnly Property configuracion() As String
            Get
                Return ResourceManager.GetString("configuracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Configurar Email.
        '''</summary>
        Friend Shared ReadOnly Property configuraremail() As String
            Get
                Return ResourceManager.GetString("configuraremail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Confirmar.
        '''</summary>
        Friend Shared ReadOnly Property confirmar() As String
            Get
                Return ResourceManager.GetString("confirmar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estas seguro de reactivar la cuenta?.
        '''</summary>
        Friend Shared ReadOnly Property confirmarreactivarregistro() As String
            Get
                Return ResourceManager.GetString("confirmarreactivarregistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Credencial.
        '''</summary>
        Friend Shared ReadOnly Property credencial() As String
            Get
                Return ResourceManager.GetString("credencial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Datos.
        '''</summary>
        Friend Shared ReadOnly Property datos() As String
            Get
                Return ResourceManager.GetString("datos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Datos email.
        '''</summary>
        Friend Shared ReadOnly Property datosemail() As String
            Get
                Return ResourceManager.GetString("datosemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Datos Estadísticos.
        '''</summary>
        Friend Shared ReadOnly Property datosestadisticos() As String
            Get
                Return ResourceManager.GetString("datosestadisticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Datos guardados con exito.
        '''</summary>
        Friend Shared ReadOnly Property datosguardadosconexito() As String
            Get
                Return ResourceManager.GetString("datosguardadosconexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esta opción permite establecer la cantidad mínima de síntomas que debe ingrear un paciente para poder recibir un diagnóstico primario.
        '''</summary>
        Friend Shared ReadOnly Property desccantidadsintomas() As String
            Get
                Return ResourceManager.GetString("desccantidadsintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Idioma del sistema, este cambio requiere reiniciar la aplicación..
        '''</summary>
        Friend Shared ReadOnly Property descidiomadelsistema() As String
            Get
                Return ResourceManager.GetString("descidiomadelsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Descripción.
        '''</summary>
        Friend Shared ReadOnly Property descripcion() As String
            Get
                Return ResourceManager.GetString("descripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hemos restablecido tu contraseña. Estos son los nuevos datos de inicio de sesión:.
        '''</summary>
        Friend Shared ReadOnly Property descripcionrecuperacion() As String
            Get
                Return ResourceManager.GetString("descripcionrecuperacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Destino.
        '''</summary>
        Friend Shared ReadOnly Property destino() As String
            Get
                Return ResourceManager.GetString("destino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnósticos.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticos() As String
            Get
                Return ResourceManager.GetString("diagnosticos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnósticos Generados.
        '''</summary>
        Friend Shared ReadOnly Property diagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("diagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diciembre.
        '''</summary>
        Friend Shared ReadOnly Property diciembre() As String
            Get
                Return ResourceManager.GetString("diciembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DIRECCION.
        '''</summary>
        Friend Shared ReadOnly Property direccion() As String
            Get
                Return ResourceManager.GetString("direccion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento de Identidad.
        '''</summary>
        Friend Shared ReadOnly Property docidentidad() As String
            Get
                Return ResourceManager.GetString("docidentidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DOCUMENTO.
        '''</summary>
        Friend Shared ReadOnly Property documento() As String
            Get
                Return ResourceManager.GetString("documento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El documento ingresado ya existe. Verifica el número.
        '''</summary>
        Friend Shared ReadOnly Property documentoexiste() As String
            Get
                Return ResourceManager.GetString("documentoexiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El envio de email esta deshabilitado.
        '''</summary>
        Friend Shared ReadOnly Property elenviodeemaildeshabilitado() As String
            Get
                Return ResourceManager.GetString("elenviodeemaildeshabilitado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El equipo de.
        '''</summary>
        Friend Shared ReadOnly Property elquipode() As String
            Get
                Return ResourceManager.GetString("elquipode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El síntoma ya existe.
        '''</summary>
        Friend Shared ReadOnly Property elsistomayaexiste() As String
            Get
                Return ResourceManager.GetString("elsistomayaexiste", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a EMAIL.
        '''</summary>
        Friend Shared ReadOnly Property email() As String
            Get
                Return ResourceManager.GetString("email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email de Contacto.
        '''</summary>
        Friend Shared ReadOnly Property emaildecontacto() As String
            Get
                Return ResourceManager.GetString("emaildecontacto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a El email se envio correctamente .
        '''</summary>
        Friend Shared ReadOnly Property emailenviadocorrectamente() As String
            Get
                Return ResourceManager.GetString("emailenviadocorrectamente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Emergencia.
        '''</summary>
        Friend Shared ReadOnly Property emergencia() As String
            Get
                Return ResourceManager.GetString("emergencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingles.
        '''</summary>
        Friend Shared ReadOnly Property en() As String
            Get
                Return ResourceManager.GetString("en", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enero.
        '''</summary>
        Friend Shared ReadOnly Property enero() As String
            Get
                Return ResourceManager.GetString("enero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Enfermedades.
        '''</summary>
        Friend Shared ReadOnly Property enfermedades() As String
            Get
                Return ResourceManager.GetString("enfermedades", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error de acceso.
        '''</summary>
        Friend Shared ReadOnly Property erroracceso() As String
            Get
                Return ResourceManager.GetString("erroracceso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se puede acceder al archivo, puede que este en uso....
        '''</summary>
        Friend Shared ReadOnly Property erroraccesoarchivo() As String
            Get
                Return ResourceManager.GetString("erroraccesoarchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al guardar los datos.
        '''</summary>
        Friend Shared ReadOnly Property erroralguardardatos() As String
            Get
                Return ResourceManager.GetString("erroralguardardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No se encuentra el archivo de configuracion. No puede continuar.
        '''</summary>
        Friend Shared ReadOnly Property errorarchivo() As String
            Get
                Return ResourceManager.GetString("errorarchivo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al borrar el registro.
        '''</summary>
        Friend Shared ReadOnly Property errorborrarregistro() As String
            Get
                Return ResourceManager.GetString("errorborrarregistro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error el intentar borrar el usuario.
        '''</summary>
        Friend Shared ReadOnly Property errorborrarusuario() As String
            Get
                Return ResourceManager.GetString("errorborrarusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hubo un error al pretender cambiar la contraseña.
        '''</summary>
        Friend Shared ReadOnly Property errorcambiarpassword() As String
            Get
                Return ResourceManager.GetString("errorcambiarpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Existe un error en la configuracion, no se pudo guardar. Verifica.
        '''</summary>
        Friend Shared ReadOnly Property errorconfiguracion() As String
            Get
                Return ResourceManager.GetString("errorconfiguracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al crear el usuario en la base de datos.
        '''</summary>
        Friend Shared ReadOnly Property errorcrearusuario() As String
            Get
                Return ResourceManager.GetString("errorcrearusuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al intentar enviar el mail.
        '''</summary>
        Friend Shared ReadOnly Property errorenviodeemail() As String
            Get
                Return ResourceManager.GetString("errorenviodeemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al exportar datos.
        '''</summary>
        Friend Shared ReadOnly Property errorexportardatos() As String
            Get
                Return ResourceManager.GetString("errorexportardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al recuperar los datos.
        '''</summary>
        Friend Shared ReadOnly Property errorrecuperardatos() As String
            Get
                Return ResourceManager.GetString("errorrecuperardatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Error al verificar el documento.
        '''</summary>
        Friend Shared ReadOnly Property errorverificardocumento() As String
            Get
                Return ResourceManager.GetString("errorverificardocumento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Español.
        '''</summary>
        Friend Shared ReadOnly Property es() As String
            Get
                Return ResourceManager.GetString("es", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ESQUINA.
        '''</summary>
        Friend Shared ReadOnly Property esquina() As String
            Get
                Return ResourceManager.GetString("esquina", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Exportar a BD.
        '''</summary>
        Friend Shared ReadOnly Property exportarabasededatos() As String
            Get
                Return ResourceManager.GetString("exportarabasededatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Faltan datos para poder importar .
        '''</summary>
        Friend Shared ReadOnly Property faltandatosarapoderimportar() As String
            Get
                Return ResourceManager.GetString("faltandatosarapoderimportar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Faltan datos requeridos o hay datos incorrectos, verifica....
        '''</summary>
        Friend Shared ReadOnly Property faltandatosrequeridos() As String
            Get
                Return ResourceManager.GetString("faltandatosrequeridos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Febrero.
        '''</summary>
        Friend Shared ReadOnly Property febrero() As String
            Get
                Return ResourceManager.GetString("febrero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FECHA.
        '''</summary>
        Friend Shared ReadOnly Property fecha() As String
            Get
                Return ResourceManager.GetString("fecha", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FECHA NAC..
        '''</summary>
        Friend Shared ReadOnly Property fechanacimiento() As String
            Get
                Return ResourceManager.GetString("fechanacimiento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Formato incorrecto para importar.
        '''</summary>
        Friend Shared ReadOnly Property formatoincorrectoparaimportar() As String
            Get
                Return ResourceManager.GetString("formatoincorrectoparaimportar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Gracias por preferirnos.
        '''</summary>
        Friend Shared ReadOnly Property graciasporpreferinos() As String
            Get
                Return ResourceManager.GetString("graciasporpreferinos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guardar.
        '''</summary>
        Friend Shared ReadOnly Property guardar() As String
            Get
                Return ResourceManager.GetString("guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Habilitado.
        '''</summary>
        Friend Shared ReadOnly Property habilitado() As String
            Get
                Return ResourceManager.GetString("habilitado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hay cambios sin guardar, deseas continuar?.
        '''</summary>
        Friend Shared ReadOnly Property haycambiossinguardar() As String
            Get
                Return ResourceManager.GetString("haycambiossinguardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Histórico de Chats.
        '''</summary>
        Friend Shared ReadOnly Property historicodechats() As String
            Get
                Return ResourceManager.GetString("historicodechats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Idioma del Sistema.
        '''</summary>
        Friend Shared ReadOnly Property idiomasistema() As String
            Get
                Return ResourceManager.GetString("idiomasistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Los datos se importaron correctamente.
        '''</summary>
        Friend Shared ReadOnly Property importacionexitosa() As String
            Get
                Return ResourceManager.GetString("importacionexitosa", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Importar datos de archivo CSV.
        '''</summary>
        Friend Shared ReadOnly Property importarcsv() As String
            Get
                Return ResourceManager.GetString("importarcsv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Información Patologías.
        '''</summary>
        Friend Shared ReadOnly Property informacionpatologias() As String
            Get
                Return ResourceManager.GetString("informacionpatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Informe de Chats.
        '''</summary>
        Friend Shared ReadOnly Property informechat() As String
            Get
                Return ResourceManager.GetString("informechat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Informe de Diagnósticos Generados.
        '''</summary>
        Friend Shared ReadOnly Property informediagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("informediagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Informes.
        '''</summary>
        Friend Shared ReadOnly Property informes() As String
            Get
                Return ResourceManager.GetString("informes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Informe de Diagnósticos.
        '''</summary>
        Friend Shared ReadOnly Property informeuso() As String
            Get
                Return ResourceManager.GetString("informeuso", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ingresar.
        '''</summary>
        Friend Shared ReadOnly Property ingresar() As String
            Get
                Return ResourceManager.GetString("ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rango IP Gestion.
        '''</summary>
        Friend Shared ReadOnly Property ipgestion() As String
            Get
                Return ResourceManager.GetString("ipgestion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Rango IP Medicos.
        '''</summary>
        Friend Shared ReadOnly Property ipmedicos() As String
            Get
                Return ResourceManager.GetString("ipmedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a IP Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property ippacientes() As String
            Get
                Return ResourceManager.GetString("ippacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Julio.
        '''</summary>
        Friend Shared ReadOnly Property julio() As String
            Get
                Return ResourceManager.GetString("julio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Junio.
        '''</summary>
        Friend Shared ReadOnly Property junio() As String
            Get
                Return ResourceManager.GetString("junio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lenguaje.
        '''</summary>
        Friend Shared ReadOnly Property lenguaje() As String
            Get
                Return ResourceManager.GetString("lenguaje", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lista de Administrativos.
        '''</summary>
        Friend Shared ReadOnly Property listaadministrativos() As String
            Get
                Return ResourceManager.GetString("listaadministrativos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LISTA DE MEDICOS.
        '''</summary>
        Friend Shared ReadOnly Property listademedicos() As String
            Get
                Return ResourceManager.GetString("listademedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Listar médicos.
        '''</summary>
        Friend Shared ReadOnly Property listamedicos() As String
            Get
                Return ResourceManager.GetString("listamedicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lista de pacientes.
        '''</summary>
        Friend Shared ReadOnly Property listapacientes() As String
            Get
                Return ResourceManager.GetString("listapacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lista de patologías.
        '''</summary>
        Friend Shared ReadOnly Property listapatologias() As String
            Get
                Return ResourceManager.GetString("listapatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Listar Todos.
        '''</summary>
        Friend Shared ReadOnly Property listartodos() As String
            Get
                Return ResourceManager.GetString("listartodos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lista de síntomas.
        '''</summary>
        Friend Shared ReadOnly Property listasintomas() As String
            Get
                Return ResourceManager.GetString("listasintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Documento de identidad o contraseña incorrectos, verifica.
        '''</summary>
        Friend Shared ReadOnly Property loginincorrecto() As String
            Get
                Return ResourceManager.GetString("loginincorrecto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Log del sistema.
        '''</summary>
        Friend Shared ReadOnly Property logsistema() As String
            Get
                Return ResourceManager.GetString("logsistema", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Marzo.
        '''</summary>
        Friend Shared ReadOnly Property marzo() As String
            Get
                Return ResourceManager.GetString("marzo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mayo.
        '''</summary>
        Friend Shared ReadOnly Property mayo() As String
            Get
                Return ResourceManager.GetString("mayo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Médico.
        '''</summary>
        Friend Shared ReadOnly Property medico() As String
            Get
                Return ResourceManager.GetString("medico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Médicos.
        '''</summary>
        Friend Shared ReadOnly Property medicos() As String
            Get
                Return ResourceManager.GetString("medicos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Vas a generar una nueva contraseña para el usuario, este cambio no se puede revertir, deseas continuar ?.
        '''</summary>
        Friend Shared ReadOnly Property mensajerestablecerpassword() As String
            Get
                Return ResourceManager.GetString("mensajerestablecerpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mes.
        '''</summary>
        Friend Shared ReadOnly Property mes() As String
            Get
                Return ResourceManager.GetString("mes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Mes y Año de Consulta.
        '''</summary>
        Friend Shared ReadOnly Property mesanoconsulta() As String
            Get
                Return ResourceManager.GetString("mesanoconsulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Meses.
        '''</summary>
        Friend Shared ReadOnly Property meses() As String
            Get
                Return ResourceManager.GetString("meses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Modificar.
        '''</summary>
        Friend Shared ReadOnly Property modificar() As String
            Get
                Return ResourceManager.GetString("modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a No.
        '''</summary>
        Friend Shared ReadOnly Property no() As String
            Get
                Return ResourceManager.GetString("no", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nombre.
        '''</summary>
        Friend Shared ReadOnly Property nombre() As String
            Get
                Return ResourceManager.GetString("nombre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a NOMBRES.
        '''</summary>
        Friend Shared ReadOnly Property nombres() As String
            Get
                Return ResourceManager.GetString("nombres", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Noviembre.
        '''</summary>
        Friend Shared ReadOnly Property noviembre() As String
            Get
                Return ResourceManager.GetString("noviembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nueva.
        '''</summary>
        Friend Shared ReadOnly Property nueva() As String
            Get
                Return ResourceManager.GetString("nueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nueva contraseña.
        '''</summary>
        Friend Shared ReadOnly Property nuevopassword() As String
            Get
                Return ResourceManager.GetString("nuevopassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº:.
        '''</summary>
        Friend Shared ReadOnly Property numero() As String
            Get
                Return ResourceManager.GetString("numero", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº EMPLEADO.
        '''</summary>
        Friend Shared ReadOnly Property numeroempelado() As String
            Get
                Return ResourceManager.GetString("numeroempelado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Nº MEDICO.
        '''</summary>
        Friend Shared ReadOnly Property numeromedico() As String
            Get
                Return ResourceManager.GetString("numeromedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Octubre.
        '''</summary>
        Friend Shared ReadOnly Property octubre() As String
            Get
                Return ResourceManager.GetString("octubre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Permite el ingreso de un nuevo telefono.
        '''</summary>
        Friend Shared ReadOnly Property opcionagregartelefono() As String
            Get
                Return ResourceManager.GetString("opcionagregartelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Elimina el telefono seleccionado en la lista.
        '''</summary>
        Friend Shared ReadOnly Property opcioneliminartelefono() As String
            Get
                Return ResourceManager.GetString("opcioneliminartelefono", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Opciones de telefonos.
        '''</summary>
        Friend Shared ReadOnly Property opcionestelefonos() As String
            Get
                Return ResourceManager.GetString("opcionestelefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Origen y Destino.
        '''</summary>
        Friend Shared ReadOnly Property origendestino() As String
            Get
                Return ResourceManager.GetString("origendestino", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Otros datos.
        '''</summary>
        Friend Shared ReadOnly Property otrosdatos() As String
            Get
                Return ResourceManager.GetString("otrosdatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Paciente.
        '''</summary>
        Friend Shared ReadOnly Property paciente() As String
            Get
                Return ResourceManager.GetString("paciente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pacientes.
        '''</summary>
        Friend Shared ReadOnly Property pacientes() As String
            Get
                Return ResourceManager.GetString("pacientes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Parametros.
        '''</summary>
        Friend Shared ReadOnly Property parametros() As String
            Get
                Return ResourceManager.GetString("parametros", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property password() As String
            Get
                Return ResourceManager.GetString("password", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologia reactivada con exito.
        '''</summary>
        Friend Shared ReadOnly Property patologiareactivadaconexito() As String
            Get
                Return ResourceManager.GetString("patologiareactivadaconexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologías.
        '''</summary>
        Friend Shared ReadOnly Property patologias() As String
            Get
                Return ResourceManager.GetString("patologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologías mas diagnosticadas, últimos 12 meses.
        '''</summary>
        Friend Shared ReadOnly Property patologiasdiagnosticadas() As String
            Get
                Return ResourceManager.GetString("patologiasdiagnosticadas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Patologías por síntoma.
        '''</summary>
        Friend Shared ReadOnly Property patologiasporsintoma() As String
            Get
                Return ResourceManager.GetString("patologiasporsintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ponderación.
        '''</summary>
        Friend Shared ReadOnly Property ponderacion() As String
            Get
                Return ResourceManager.GetString("ponderacion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pre-existentes.
        '''</summary>
        Friend Shared ReadOnly Property preexistentes() As String
            Get
                Return ResourceManager.GetString("preexistentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Puerto SMTP.
        '''</summary>
        Friend Shared ReadOnly Property puertosmtp() As String
            Get
                Return ResourceManager.GetString("puertosmtp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ranking de patologías.
        '''</summary>
        Friend Shared ReadOnly Property rankingdepatologias() As String
            Get
                Return ResourceManager.GetString("rankingdepatologias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Generacion de nueva contraseña.
        '''</summary>
        Friend Shared ReadOnly Property recuperacionpassword() As String
            Get
                Return ResourceManager.GetString("recuperacionpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recuperar.
        '''</summary>
        Friend Shared ReadOnly Property recuperar() As String
            Get
                Return ResourceManager.GetString("recuperar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registro eliminado correctamente !.
        '''</summary>
        Friend Shared ReadOnly Property registroeleminado() As String
            Get
                Return ResourceManager.GetString("registroeleminado", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Registros Históricos.
        '''</summary>
        Friend Shared ReadOnly Property registroshistoricos() As String
            Get
                Return ResourceManager.GetString("registroshistoricos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reescribe la contraseña.
        '''</summary>
        Friend Shared ReadOnly Property renuevopassword() As String
            Get
                Return ResourceManager.GetString("renuevopassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Restablecer contraseña.
        '''</summary>
        Friend Shared ReadOnly Property restablecerpassword() As String
            Get
                Return ResourceManager.GetString("restablecerpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Salir.
        '''</summary>
        Friend Shared ReadOnly Property salir() As String
            Get
                Return ResourceManager.GetString("salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La configuracion se guardo correctamente..
        '''</summary>
        Friend Shared ReadOnly Property seguardolaconfiguracion() As String
            Get
                Return ResourceManager.GetString("seguardolaconfiguracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Seguro de eliminar el registro?.
        '''</summary>
        Friend Shared ReadOnly Property segurodeeliminiar() As String
            Get
                Return ResourceManager.GetString("segurodeeliminiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Estas seguro de reactivar la patologia?.
        '''</summary>
        Friend Shared ReadOnly Property segurodereactivarpatologia() As String
            Get
                Return ResourceManager.GetString("segurodereactivarpatologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Selecciona el Informe.
        '''</summary>
        Friend Shared ReadOnly Property seleccionaelinforme() As String
            Get
                Return ResourceManager.GetString("seleccionaelinforme", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Servidor.
        '''</summary>
        Friend Shared ReadOnly Property servidor() As String
            Get
                Return ResourceManager.GetString("servidor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Servidor SMTP.
        '''</summary>
        Friend Shared ReadOnly Property servidorsmtp() As String
            Get
                Return ResourceManager.GetString("servidorsmtp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sesión.
        '''</summary>
        Friend Shared ReadOnly Property sesion() As String
            Get
                Return ResourceManager.GetString("sesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sesiones.
        '''</summary>
        Friend Shared ReadOnly Property sesiones() As String
            Get
                Return ResourceManager.GetString("sesiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Setiembre.
        '''</summary>
        Friend Shared ReadOnly Property setiembre() As String
            Get
                Return ResourceManager.GetString("setiembre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Si.
        '''</summary>
        Friend Shared ReadOnly Property si() As String
            Get
                Return ResourceManager.GetString("si", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Síntomas.
        '''</summary>
        Friend Shared ReadOnly Property sintomas() As String
            Get
                Return ResourceManager.GetString("sintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sintomas nunca seleccionados.
        '''</summary>
        Friend Shared ReadOnly Property sintomasnuncaseleccionados() As String
            Get
                Return ResourceManager.GetString("sintomasnuncaseleccionados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sin Urgencia.
        '''</summary>
        Friend Shared ReadOnly Property sinurgencia() As String
            Get
                Return ResourceManager.GetString("sinurgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Software de Gestión Médica.
        '''</summary>
        Friend Shared ReadOnly Property softwaregestionmedica() As String
            Get
                Return ResourceManager.GetString("softwaregestionmedica", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Solo Activos.
        '''</summary>
        Friend Shared ReadOnly Property soloactivos() As String
            Get
                Return ResourceManager.GetString("soloactivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Solo Inactivos.
        '''</summary>
        Friend Shared ReadOnly Property soloinactivos() As String
            Get
                Return ResourceManager.GetString("soloinactivos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Informe de diagnósticos generados en los últimos 12 meses móviles.
        '''</summary>
        Friend Shared ReadOnly Property subitutlodiagnosticosgenerados() As String
            Get
                Return ResourceManager.GetString("subitutlodiagnosticosgenerados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cantidad minima de sintomas que debe indicar un paciente para recibir un diagnostico.
        '''</summary>
        Friend Shared ReadOnly Property subsitulosintomas() As String
            Get
                Return ResourceManager.GetString("subsitulosintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Configuracion de direcciones IP de conexion para las difentes aplicaciones.
        '''</summary>
        Friend Shared ReadOnly Property subtituloconexiones() As String
            Get
                Return ResourceManager.GetString("subtituloconexiones", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guarda la configuaracion necesaria para el envio de Email desde la app medico.
        '''</summary>
        Friend Shared ReadOnly Property subtituloemail() As String
            Get
                Return ResourceManager.GetString("subtituloemail", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat generados en el mes requerido.
        '''</summary>
        Friend Shared ReadOnly Property subtituloinfochatmes() As String
            Get
                Return ResourceManager.GetString("subtituloinfochatmes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat registrados en los últimos 12 meses móviles.
        '''</summary>
        Friend Shared ReadOnly Property subtituloinfochatmeses() As String
            Get
                Return ResourceManager.GetString("subtituloinfochatmeses", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Muestra la lista de sintomas que los pacientes nunca indicaron.
        '''</summary>
        Friend Shared ReadOnly Property subtitulolistasintomasnoseleccionados() As String
            Get
                Return ResourceManager.GetString("subtitulolistasintomasnoseleccionados", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Teléfonos.
        '''</summary>
        Friend Shared ReadOnly Property telefonos() As String
            Get
                Return ResourceManager.GetString("telefonos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Chat Generados.
        '''</summary>
        Friend Shared ReadOnly Property tituloinfochat() As String
            Get
                Return ResourceManager.GetString("tituloinfochat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recuperacion de contraseña.
        '''</summary>
        Friend Shared ReadOnly Property titulorecuperarpassword() As String
            Get
                Return ResourceManager.GetString("titulorecuperarpassword", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Habilita el ingreso de un nuevo registro.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonagregar() As String
            Get
                Return ResourceManager.GetString("toolbotonagregar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Borrar el registro en pantalla.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonborrar() As String
            Get
                Return ResourceManager.GetString("toolbotonborrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Buscar por el nombre ingresado.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonbuscar() As String
            Get
                Return ResourceManager.GetString("toolbotonbuscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cancela los cambios.
        '''</summary>
        Friend Shared ReadOnly Property toolbotoncancelar() As String
            Get
                Return ResourceManager.GetString("toolbotoncancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Guarda los cambios.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonguardar() As String
            Get
                Return ResourceManager.GetString("toolbotonguardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Habilita la modificación de una patología.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonmodificar() As String
            Get
                Return ResourceManager.GetString("toolbotonmodificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Inicia una nueva búsqueda.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonnueva() As String
            Get
                Return ResourceManager.GetString("toolbotonnueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reactiva la cuenta en pantalla.
        '''</summary>
        Friend Shared ReadOnly Property toolbotonreactivar() As String
            Get
                Return ResourceManager.GetString("toolbotonreactivar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tu cuenta en Vida Sana ha sido activada, ahora podras ingresar a la aplicacion con la siguiente información.
        '''</summary>
        Friend Shared ReadOnly Property tucuentaactivada() As String
            Get
                Return ResourceManager.GetString("tucuentaactivada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Urgencia.
        '''</summary>
        Friend Shared ReadOnly Property urgencia() As String
            Get
                Return ResourceManager.GetString("urgencia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Urgencia Menor.
        '''</summary>
        Friend Shared ReadOnly Property urgenciamenor() As String
            Get
                Return ResourceManager.GetString("urgenciamenor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Usuario.
        '''</summary>
        Friend Shared ReadOnly Property usuario() As String
            Get
                Return ResourceManager.GetString("usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a La cuenta se ha re activado con exito !.
        '''</summary>
        Friend Shared ReadOnly Property usuariorestauradoexito() As String
            Get
                Return ResourceManager.GetString("usuariorestauradoexito", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver Chat.
        '''</summary>
        Friend Shared ReadOnly Property verchat() As String
            Get
                Return ResourceManager.GetString("verchat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver Informes.
        '''</summary>
        Friend Shared ReadOnly Property verinformes() As String
            Get
                Return ResourceManager.GetString("verinformes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver Médico.
        '''</summary>
        Friend Shared ReadOnly Property verMedico() As String
            Get
                Return ResourceManager.GetString("verMedico", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ver Patología.
        '''</summary>
        Friend Shared ReadOnly Property verpatologia() As String
            Get
                Return ResourceManager.GetString("verpatologia", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
