use dbTriage;

INSERT INTO `patologia` (`id`, `nombre`, `ponderacion`, `descripcion`, `activo`) VALUES
(1, 'Contracturas', 10, 'Dolor Muscular en todo el cuerpo', 1),
(2, 'Gripe A', 40, 'La gripe A es una enfermedad infecciosa causada por un virus de la influenza tipo A,', 1),
(3, 'Covid-19', 10, 'Los síntomas aparecen entre dos y catorce días, con un promedio de cinco días, después de la exposición al virus.21?22?23?24? Existe evidencia limitada que sugiere que el virus podría transmitirse uno o dos días antes de que se tengan síntomas, ya que la viremia alcanza un pico al final del período de incubación.2', 1),
(4, 'Ataque la Higado', 10, 'Comé despacio y mastica muy bien. El hígado no es el responsable de tus molestias. Es un problema digestivo. Deberás tener presente todos estos consejos para evitar su progresión.', 1),
(5, 'Sinusitis', 20, 'Inflamación nasal.Secreción espesa y descolorida de la nariz. Secreción por la parte posterior de la garganta (secreción posnasal). Obstrucción o congestión nasal, que dificultad para respirar por la nariz. Dolor, sensibilidad e inflamación alrededor de los ojos, las mejillas, la nariz o la frente', 1),
(6, 'Asma', 40, 'Falta de aire. Dolor u opresión en el pecho. Problemas para dormir causados por falta de aire, tos o silbido al respirar.', 1),
(7, 'Hemorroides', 10, 'Las hemorroides, también llamadas almorranas, son venas hinchadas en el ano y la parte inferior del recto, similares a las venas varicosas. Las hemorroides pueden desarrollarse dentro del recto (hemorroides internas) o debajo de la piel alrededor del ano (hemorroides externas).', 1),
(11, 'Accidente cerebrovascular', 40, 'Un accidente cerebrovascular ocurre cuando el suministro de sangre a una parte del cerebro se interrumpe o se reduce, lo que impide que el tejido cerebral reciba oxígeno y nutrientes. Las células cerebrales comienzan a morir en minutos.', 1),
(15, 'Artritis reumatoide', 20, 'La artritis reumatoide es una forma de artritis que causa dolor, inflamación, rigidez y pérdida de la función de las articulaciones. Puede afectar cualquier articulación, pero es común en las muñecas y los dedos.', 1),
(16, 'Broncoespamo', 10, 'Las glándulas bronquiales se encargan de segregar una mucosidad que acaba por bloquear los bronquios impidiendo que el aire circule con normalidad. ', 1),
(18, 'Dengue', 40, 'El dengue es una enfermedad infecciosa producida por el virus del dengue (DENV). Pertenece al género Flavivirus, de la familia Flaviviridae que, a la vez, pertenece al grupo de los Arbovirus (virus trasmitidos por artrópodos). Las partículas virales contienen RNA de cadena simple, son envueltas y tienen aproximadamente 40-50 nm de diámetro.', 1),
(19, 'Patologia Uno', 20, 'Ingreso de nuevo patologia <sv<sd', 0),
(20, 'Prueba de pat', 10, 'Prueba de patologia nueva', 0),
(22, 'Prueba de patologia', 20, 'Ingreso de patologia 17/06/2020 con sus sintomas relacionados', 0),
(24, 'Ingreso de patologia', 20, 'Ingreso de patologia 1 con sintomas diferentes', 0),
(25, 'Prueba 2', 40, 'Ingreso de patologia 2', 1),
(26, 'Prueba 3', 30, 'Ingreso de patologia 3 17/06/2020 con sintomas', 1),
(27, 'Rinitis', 30, 'Usted presenta un cuadro de  Rinitis. La rinitis es una inflamación del revestimiento mucoso de la nariz, caracterizada clínicamente por uno o más síntomas: rinorrea, estornudo, prurito (picor) nasal, tos irritativa, drenaje (secreción) postnasal.', 1),
(28, 'picazon', 10, 'urticaria en el cuerpo, principalmente en manos', 0),
(29, 'test', 1000, 'asrgaedrgadsf', 0),
(30, 'Broncoespasmo', 10, 'Las glándulas bronquiales se encargan de segregar una mucosidad que acaba por bloquear los bronquios impidiendo que el aire circule con normalidad. ', 0),
(31, 'Patologia inactiva', 10, 'asrgasg', 0),
(32, 'Acné', 10, 'El acné es una enfermedad que se caracteriza por la aparición de lesiones en la piel como consecuencia de una foliculitis, una inflamación y posterior infección del poro folicular (orificio de salida del pelo). Estas lesiones suelen ser granos, espinillas negras y parches rojos e inflamados, como quistes.', 1),
(33, 'Aftas bucales', 10, 'Las aftas bucales son úlceras que se producen en la mucosa de la boca y constituyen una de las enfermedades bucales que  más frecuencia tiene junto con las caries. Son de tamaño pequeño (unos 5 milímetros), el color suele ser blanquecino y aparecen rodeadas por un área roja. Además, no son contagiosas.', 1),
(34, 'Nueva Patologia', 30, 'Detalle', 1),
(35, 'Nueva patologia', 20, 'Detalle', 0),
(36, 'Gripe común', 10, 'La gripe es causada por un virus de la influenza.\r\nLa mayoría de las personas contraen la gripe cuando inhalan gotitas provenientes de la tos o los estornudos de alguien que tenga gripe. Usted también la puede contraer si toca algo que contenga el virus y luego se toca la boca, la nariz o los ojos.', 1),
(37, 'para borrar', 20, 'Patologia para borrar', 0),
(38, 'prueba', 20, 'adasds', 0),
(39, 'drtjhndsrt', 10, 'aerhaerhearhaerhea', 1),
(40, 'Piedras en Riñones', 40, 'Tus riñones remueven los desechos y líquidos de tu cuerpo para hacer orina.  Algunas veces cuando tienes demasiado de algún desecho y no suficiente líquidos en tu sangre, estos deshechos pueden acumularse y aglutinan en tus riñones.  Estos bodoques de deshechos son llamadas piedras en los riñones o también conocidos como cálculos renales.\r\n\r\n', 1);